- docs/_templates/sidebar/navigation.html
> docs: fix sidebar link

- docarray/array/document.py
- docs/fundamentals/document/construct.md
- docs/get-started/what-is.md
- tests/unit/array/test_advance_indexing.py
> fix: fix edge case when two elements are strings

- docarray/array/mixins/io/csv.py
- docarray/array/mixins/plot.py
- setup.py
> feat(array): auto render in colab and jupyter

- docarray/array/mixins/io/pushpull.py
Use the cloud Api Url fetched from https://api.jina.ai/hub/hubble.json
Traffic doesn't pass through CloudFlare anymore.
> fix(pushpull): allow uploading docarray max size 4GB

- docarray/__init__.py
- docarray/array/mixins/io/csv.py
- docarray/array/mixins/io/json.py
- docarray/base.py
- docarray/document/mixins/porting.py
- docarray/document/mixins/pydantic.py
- docarray/document/pydantic_model.py
- docs/fundamentals/document/serialization.md
- docs/fundamentals/documentarray/serialization.md
- tests/unit/array/test_from_to_bytes.py
- tests/unit/document/test_porting.py
- tests/unit/document/test_protobuf.py
- tests/unit/test_pydantic.py
> feat: use schema-ed json as default to_dict/json

- docarray/document/pydantic_model.py
- tests/__init__.py
- tests/unit/test_pydantic.py
> fix(document): serialize tag value in the correct priority

- docarray/array/mixins/plot.py
- tests/unit/array/mixins/test_plot.py
> fix(array): allow plot to use uri or tensor as the source

- docarray/document/mixins/featurehash.py
- tests/unit/document/test_feature_hashing.py
> fix(document): fix feature hash mixin

- docarray/array/storage/memory/backend.py
- docarray/array/storage/memory/getsetdel.py
- docarray/array/storage/memory/seqlike.py
- tests/unit/array/mixins/test_del.py
- tests/unit/array/test_sequence.py
Current version of docarray has a wrong behavior while deleting item via ids ==>
@JohannesMessner and I added some test to cover all of the del case from the documentation + a fix when deleting by ids
> fix: del with ids

- docarray/array/mixins/plot.py
- docarray/array/storage/base/backend.py
- docarray/array/storage/memory/backend.py
- docarray/array/storage/sqlite/backend.py
- docarray/array/storage/weaviate/backend.py
Fixes da.summary() when there is no attributes
> fix: fix summary for storage backends

- docarray/array/storage/memory/seqlike.py
slack discussion: https://jinaai.slack.com/archives/C02AC4T8Y5T/p1643893118678839
> perf: implement append to avoid invalidating id2offset

- docarray/array/storage/weaviate/seqlike.py
reduces batch_size of weaviate client batch object
> fix: decrease batch_size of weaviate client

- tests/unit/array/mixins/test_plot.py
- tests/unit/array/mixins/test_traverse.py
This PR is the first one in the series to enable `AllMixins` tests for various storages. This one enables traverse and some plot tests for storages.
Enabling these tests will increase tests execution time, so tests time optimization discussed [here](https://jinaai.slack.com/archives/C02AC4T8Y5T/p1644839047201979) would be very useful.
>  test: enable traverse mixin tests for storages

- docs/fundamentals/documentarray/access-elements.md
closes: https://github.com/jina-ai/docarray/issues/123
> docs: fix split by tags example

- .github/workflows/ci.yml
- scripts/get-all-test-paths.sh
Reverts jina-ai/docarray#118
this codecov drops 69%
> Revert "test: reduce test time"

- docarray/document/pydantic_model.py
- tests/unit/test_pydantic.py
close https://github.com/jina-ai/docarray/issues/136
> fix: tags pydantic

- tests/unit/array/mixins/test_getset.py
Enable a few remaining tests that were not enabled before in `test_getset.py`
> test: enable more tests for getset mixin

- docarray/array/mixins/io/pushpull.py
- tests/unit/array/mixins/test_pushpull.py
* also added ability change server host
related https://github.com/jina-ai/hubble/issues/301
> fix(pushpull): raise error if push failed

- docarray/array/mixins/content.py
- docarray/document/mixins/plot.py
- tests/unit/array/mixins/test_content.py
- tests/unit/array/mixins/test_getset.py
- tests/unit/document/test_summary.py
- text getter
- plot local audio/video file (e.g., `../data/helllo.mp4`) by `display()`
> fix(array): fix text getter

- docarray/array/storage/base/getsetdel.py
- tests/unit/array/mixins/test_del.py
This PR fixes https://github.com/jina-ai/docarray/issues/152
> fix: bug with del with bool mask

- docarray/array/storage/weaviate/backend.py
- docs/advanced/document-store/weaviate.md
refactor: split client config into separate parameters
> refactor: split client config into separate parameters

- docarray/array/storage/qdrant/find.py
- docarray/array/storage/weaviate/find.py
- tests/unit/array/mixins/test_match.py
fix: support torch.Tensor and other embeddings in match
> fix: support torch.Tensor and other embeddings in match

- docarray/array/mixins/__init__.py
- docarray/array/mixins/io/dict.py
- docarray/array/mixins/io/json.py
- docs/fundamentals/documentarray/serialization.md
- tests/unit/array/mixins/test_io.py
- tests/unit/array/test_from_to_bytes.py
this PR implements https://github.com/jina-ai/docarray/issues/156
> feat: add from to dict io

- docarray/array/storage/qdrant/backend.py
- docarray/array/storage/qdrant/getsetdel.py
- setup.py
- tests/unit/array/docker-compose.yml
Updates qdrant client and fixes breaking changes.
- Client release note: https://github.com/qdrant/qdrant_client/releases/tag/v0.6.0
- Qdrant release note: https://github.com/qdrant/qdrant/releases/tag/v0.6.0
> Qdrant 0.6.0

- docarray/base.py
- tests/unit/document/test_docdata.py
attempt to close https://github.com/jina-ai/docarray/issues/173
> fix: set doc id first

- tests/unit/array/mixins/test_eval_class.py
Work in progress. Working on making the tests pass at the moment.
> test: enable evaluate mixin tests for backends

- docs/_templates/page.html
- docs/conf.py
Fixed below issues for qabot:
1. flashing when scrolling on ios
2. disappearing on search and 404 page
And removed obsolete theme configuration for qabot.
> docs(qabot): fix flash on ios and disappear on search&404 page

- docarray/array/mixins/find.py
- docarray/array/queryset/lookup.py
- docarray/array/queryset/parser.py
- tests/unit/array/mixins/test_filter.py
- tests/unit/array/test_lookup.py
- tests/unit/array/test_queryset.py
```python
result = docs.find({'text': {'$exists': True}})
result = docs.find({'text': {'$exists': False}})
```
**Note: ** empty string content is also considered as not exists.
> feat: add `$exists` logic

- docarray/array/queryset/lookup.py
- docarray/array/queryset/parser.py
- docs/fundamentals/document/index.md
- docs/fundamentals/documentarray/access-elements.md
- docs/fundamentals/documentarray/find.md
- docs/fundamentals/documentarray/index.md
- docs/fundamentals/documentarray/matching.md
- tests/unit/array/test_lookup.py
> docs(array): add docs for find function

- docs/advanced/document-store/weaviate.md
docs: add weaviate minimum working example
> docs: add weaviate minimum working example

- tests/unit/array/mixins/test_content.py
- tests/unit/array/mixins/test_embed.py
- tests/unit/array/mixins/test_empty.py
- tests/unit/array/mixins/test_eval_class.py
- tests/unit/array/mixins/test_getset.py
- tests/unit/array/mixins/test_io.py
- tests/unit/array/mixins/test_magic.py
- tests/unit/array/mixins/test_parallel.py
- tests/unit/array/mixins/test_plot.py
- tests/unit/array/mixins/test_sample.py
- tests/unit/array/mixins/test_text.py
- tests/unit/array/mixins/test_traverse.py
- tests/unit/array/test_advance_indexing.py
- tests/unit/array/test_construct.py
- tests/unit/array/test_pull_out.py
- tests/unit/array/test_sequence.py
WIP, to be rebased onto `feat-elastic-storage` branch once it's ready
> test: enable elastic storage

- docarray/document/mixins/pydantic.py
- docarray/document/pydantic_model.py
closes: https://github.com/jina-ai/docarray/issues/221
> fix: encode and decode only once

- .github/workflows/ci.yml
- scripts/black.sh
> ci: add basic import test

- docs/advanced/document-store/extend.md
> docs: update extend docs

- docarray/array/mixins/io/pushpull.py
- docarray/exceptions.py
- tests/unit/array/mixins/test_pushpull.py
Related https://github.com/jina-ai/hubble/issues/353
> feat(hubble): push/pull user authentication

- README.md
- docs/fundamentals/documentarray/serialization.md
> docs: fix push/pull

- docarray/array/mixins/traverse.py
- tests/unit/document/test_multi_modal.py
refactor: only allow selection of attributes with bracket
> refactor: only allow selection of attributes with bracket

- docs/fundamentals/dataclass/access.md
- docs/fundamentals/dataclass/construct.md
- docs/fundamentals/dataclass/index.md
- docs/fundamentals/dataclass/new-type.md
> docs: improve dataclass docs

- docarray/array/storage/elastic/backend.py
- docarray/array/storage/elastic/seqlike.py
feat: upload in batches for elastic
> feat: upload in batches for elastic

- docarray/array/storage/annlite/backend.py
- docarray/array/storage/elastic/backend.py
- docarray/array/storage/qdrant/backend.py
- docarray/array/storage/weaviate/backend.py
- docarray/helper.py
- docs/advanced/document-store/annlite.md
- docs/advanced/document-store/elasticsearch.md
- docs/advanced/document-store/qdrant.md
- docs/advanced/document-store/weaviate.md
feat: add hnsw params to storage backends
> feat: add hnsw params to storage backends

- docarray/array/storage/qdrant/__init__.py
- docarray/array/storage/qdrant/backend.py
- docarray/array/storage/qdrant/helper.py
refactor: adapt to qdrant client 0.7
> refactor: adapt to qdrant client 0.7

- docarray/array/mixins/parallel.py
- tests/unit/array/mixins/test_parallel.py
fix: support partial functions in parallel methods
> fix: support partial functions in parallel methods

- docs/advanced/document-store/benchmark.md
> docs: fix link and clarify

- docs/advanced/document-store/benchmark.md
> docs: some fixes and typos for benchmark page

- docs/advanced/document-store/benchmark.md
- scripts/benchmarking.py
> docs: benchmark fixes

- docarray/array/storage/weaviate/backend.py
- docs/advanced/document-store/benchmark.md
- docs/advanced/document-store/weaviate.md
> feat: add timeout parameter

- docarray/array/mixins/find.py
- tests/unit/array/mixins/test_find.py
Fixes https://github.com/jina-ai/docarray/issues/274
> fix: consider singleton to return singleton

- docarray/array/mixins/delitem.py
- tests/unit/array/mixins/test_del.py
This should cover  https://github.com/jina-ai/docarray/issues/303
> fix: del remove attribute

- docarray/array/storage/weaviate/find.py
fix issue of weaviate overwritting tags
> fix: weaviate tags were ovewritten

- docarray/array/mixins/parallel.py
Goals:
- Make `apply` memory efficient and suitable for storage backends
> perf: use less memory for apply

- docs/fundamentals/documentarray/access-elements.md
- docs/fundamentals/documentarray/matching.md
> docs(docarray): fix typo

- setup.py
Goals:
- upgrade qdrant client
> chore: update qdrant version

- docs/advanced/document-store/annlite.md
- docs/advanced/document-store/elasticsearch.md
- docs/advanced/document-store/qdrant.md
- docs/advanced/document-store/weaviate.md
- setup.py
chore: complete backends dependency tags
> chore: complete backends dependency tags

- docarray/array/storage/elastic/backend.py
chore: modify elastic hosts typehint
> chore: modify elastic hosts typehint

- docarray/array/storage/weaviate/backend.py
closes: https://github.com/jina-ai/docarray/issues/352
> fix: cryptographic random generator for weaviate classnames

- docarray/array/mixins/content.py
- docarray/document/mixins/helper.py
- docarray/helper.py
- tests/unit/document/test_converters.py
closes: https://github.com/jina-ai/docarray/issues/362
> fix(windows): fix windows newline issue

- docarray/__init__.py
- docarray/helper.py
> refactor: remove redundant code

- docarray/array/storage/annlite/backend.py
- docarray/array/storage/base/backend.py
- docarray/array/storage/weaviate/backend.py
- docarray/helper.py
- tests/unit/array/test_backend_configuration.py
- tests/unit/test_helper.py
closes: https://github.com/jina-ai/docarray/issues/391
> fix: cast column to its correct type before insertion in database

- docarray/dataclasses/types.py
- docarray/document/mixins/multimodal.py
- tests/unit/document/test_multi_modal.py
Goals:
to resolve #393
- ...
- ...
> fix: adding an int() cast to avoid IndexError

- docarray/array/mixins/find.py
- docarray/array/storage/weaviate/find.py
> fix: propagate limit for filter

- docarray/array/storage/memory/find.py
- docs/advanced/document-store/weaviate.md
- docs/fundamentals/documentarray/matching.md
- tests/unit/array/mixins/test_find.py
> fix: customize metric fn expect no metric_name

- docs/conf.py
POC of making a better API reference page. Will be implemented in core as well
work initiated with @davidbp  @JohannesMessner 
- ...
- ...
> Feat docs improvment

- docs/advanced/document-store/index.md
This PR adds a table with storage backends and basic functionalities.
> docs: add table with basic capabilities of different storage backends

- docarray/array/storage/elastic/backend.py
- tests/unit/array/storage/elastic/test_data_type.py
Goals:
Added more supported data type for eleastic search backend
- ...
- ...
> feat: added es data type for long, double, bool

- docarray/array/storage/qdrant/seqlike.py
- docarray/array/storage/sqlite/seqlike.py
Goals:
Small changes seen while going through the code
> refactor: small changes

- docarray/array/mixins/io/pushpull.py
- docarray/array/mixins/plot.py
- docarray/helper.py
- tests/unit/array/mixins/test_plot.py
> feat: add gif export 

- docarray/array/annlite.py
- docarray/array/document.py
- docarray/array/memory.py
- docarray/array/qdrant.py
- docarray/array/sqlite.py
- docarray/array/weaviate.py
- docarray/dataclasses/types.py
- docarray/document/__init__.py
- docs/api.rst
- docs/conf.py
- docs/fundamentals/document/index.md
- docs/index.md
> docs: create api reference landing page

- docs/advanced/document-store/weaviate.md
> docs: fix code example

- docs/requirements.txt
> fix: fix deploy to netlify

- docarray/array/mixins/getitem.py
- docs/fundamentals/documentarray/access-attributes.md
- tests/unit/array/test_base_getsetdel.py
> fix: fix getitem by ellipsis

- docarray/array/mixins/plot.py
- tests/unit/array/mixins/test_plot.py
> fix: fix plot bug recompute size

- docarray/array/mixins/plot.py
- tests/unit/array/mixins/test_plot.py
> fix(plot): convert uint8 before plotting

- docarray/array/storage/sqlite/getsetdel.py
- tests/unit/array/test_sequence.py
fixes the bug described here: https://github.com/jina-ai/docarray/issues/470
> fix: keep offset2id updated when deleting in sqlite

- docarray/document/mixins/image.py
> fix(image): fix image padding on vertical direction

- docarray/array/storage/elastic/getsetdel.py
- tests/unit/array/storage/elastic/test_get.py
Goals:
- Implement a more efficient approach on getting multiple docs by using elastic search client method `mget` rather than `get` one by one
> feat(elastic): add bulk get operation

- docarray/array/storage/elastic/getsetdel.py
Goals:
- `np.split_array` split the array evenly which leads to the number of documents is less than the `MAX_ES_RETURNED_DOCS` when `len(ids) % MAX_ES_RETURNED_DOCS != 0`
- remove the unnecessary importing of `numpy` and `math`
> fix: retrieve MAX_ES_RETURNED_DOCS docs in bulk operations

- docarray/__init__.py
> chore: bump version to 0.15.0

- docarray/array/mixins/io/pushpull.py
- tests/unit/array/mixins/test_io.py
- tests/unit/array/test_from_to_bytes.py
> feat: push meta data along with docarray

- docarray/array/mixins/setitem.py
- docarray/array/storage/base/backend.py
- docarray/array/storage/base/getsetdel.py
- tests/unit/array/mixins/test_getset.py
- tests/unit/array/test_advance_indexing.py
Issue is described here: https://github.com/jina-ai/docarray/issues/489
> fix: set subindices directly via access path

- docarray/document/mixins/video.py
yep, foundational work for JChat
> feat(video): add height_width for webcam caps

- setup.py
Goals:
- cap annlite version up to 0.3.5, since 0.3.6 is breaking
> fix: cap annlite version

- setup.py
Reverts jina-ai/docarray#497
**to be merged only when annlite 0.3.6 is yanked**
> Revert "fix: cap annlite version"

- .github/workflows/ci.yml
> chore: cleanup ci

- docarray/math/distance/torch.py
- docs/advanced/document-store/index.md
> fix(find): make device more generic

- tests/unit/array/mixins/test_io.py
- tests/unit/document/test_converters.py
Goals:
- adapt CI to hubble changes: https://github.com/jina-ai/hubble/pull/562
- remove file that is no more available from test case: https://storage.googleapis.com/showcase-3d-models/ShapeNetV2/airplane_aeroplane_plane_0.glb
> test: ci fix

- docarray/document/mixins/strawberry.py
Goals:
Fix problem in Jina introduced by new graphql release
> fix: create strawberry types with kwargs

- README.md
Goals:
This PR fix the missing link in docarray point to finetuner.
> fix: fix fiinetuner link for totally looks like

- docarray/array/storage/annlite/backend.py
- docarray/array/storage/base/backend.py
- docarray/array/storage/elastic/backend.py
- docarray/array/storage/elastic/getsetdel.py
- docarray/array/storage/qdrant/backend.py
- docarray/array/storage/qdrant/getsetdel.py
- docarray/array/storage/redis/backend.py
- docarray/array/storage/redis/getsetdel.py
- docarray/array/storage/sqlite/backend.py
- docarray/array/storage/weaviate/backend.py
- docs/advanced/document-store/annlite.md
- docs/advanced/document-store/elasticsearch.md
- docs/advanced/document-store/index.md
- docs/advanced/document-store/qdrant.md
- docs/advanced/document-store/redis.md
- docs/advanced/document-store/weaviate.md
- docs/fundamentals/documentarray/subindex.md
- setup.py
- tests/unit/array/mixins/test_find.py
- tests/unit/array/mixins/test_match.py
- tests/unit/array/storage/elastic/test_add.py
- tests/unit/array/storage/elastic/test_data_type.py
- tests/unit/array/storage/elastic/test_del.py
- tests/unit/array/storage/elastic/test_get.py
- tests/unit/array/storage/redis/test_backend.py
- tests/unit/array/storage/redis/test_getsetdel.py
- tests/unit/array/test_backend_configuration.py
Goals:
Since List[Tuple] is not something that can be passed via YAML to a Flow, we need to make sure that this is doable, so having a `Dict` like structure for `columns` is the best way to go.
> feat: columns should be a dictionary not list of tuples

- docs/advanced/document-store/index.md
add link to the benchmark so that users can quickly choose the right database storage to use
Goals:
add link to the benchmark so that users can quickly choose the right database storage to use
- ...
- ...
> docs: add benchmark reference to feature summary

- docarray/array/storage/memory/getsetdel.py
- tests/unit/array/mixins/test_del.py
closes: https://github.com/jina-ai/docarray/issues/530
> fix: keep out of mask docs in del by mask

- docarray/array/storage/redis/backend.py
- docarray/array/storage/redis/find.py
- docarray/array/storage/redis/getsetdel.py
- docs/advanced/document-store/redis.md
- tests/unit/array/mixins/test_find.py
- tests/unit/array/mixins/test_io.py
Goals:
This PR will add support of full-text search in redis according to https://github.com/jina-ai/docarray/issues/500 and add io functions in redis.
> feat(redis): add full-text search and io

- docarray/array/storage/redis/backend.py
- docarray/array/storage/redis/find.py
- docarray/array/storage/redis/getsetdel.py
- docs/advanced/document-store/redis.md
- tests/unit/array/mixins/test_content.py
- tests/unit/array/mixins/test_del.py
- tests/unit/array/mixins/test_embed.py
- tests/unit/array/mixins/test_empty.py
- tests/unit/array/mixins/test_eval_class.py
- tests/unit/array/mixins/test_find.py
- tests/unit/array/mixins/test_getset.py
- tests/unit/array/mixins/test_io.py
- tests/unit/array/mixins/test_magic.py
- tests/unit/array/mixins/test_match.py
- tests/unit/array/mixins/test_parallel.py
- tests/unit/array/mixins/test_plot.py
- tests/unit/array/mixins/test_sample.py
- tests/unit/array/mixins/test_text.py
- tests/unit/array/mixins/test_traverse.py
- tests/unit/array/storage/redis/test_backend.py
- tests/unit/array/storage/redis/test_getsetdel.py
- tests/unit/array/test_advance_indexing.py
- tests/unit/array/test_construct.py
- tests/unit/array/test_pull_out.py
- tests/unit/array/test_sequence.py
Goals:
This PR will add support for storing multiple DocumentArrays in the one Redis server instance according to https://github.com/jina-ai/docarray/issues/507
> feat: redis supports multiple DocumentArrays

- docarray/__init__.py
> chore: bump minor version

- docs/get-started/what-is.md
Goals:
- Enhance readability
- Ensure professional content quality
> docs(what-is-docarray): tidy up grammar, punctuation, wording, spelling

- tests/unit/array/storage/weaviate/test_additional_properties.py
- tests/unit/array/storage/weaviate/test_query_params.py
Goals:
- Add unit test for Weaviate Additional properties
- Add unit test for Weaviate Query Parameters
> test(weaviate): add test cases for weaviate

- docarray/array/mixins/find.py
- docarray/array/storage/elastic/backend.py
- docarray/array/storage/elastic/find.py
- tests/unit/array/storage/elastic/test_find.py
Goals:
Add test filtering in ES with `match` ES Query
> test: add tests for filtering in elasticsearch

- docarray/array/storage/memory/seqlike.py
- tests/unit/array/mixins/test_add.py
- tests/unit/document/test_plot.py
> fix(array): fix add not performing deep copy

- .github/workflows/force-docs-build.yml
- .github/workflows/label-pr.yml
Goals:
Build properly api references for docstores
> docs: build proper docs section docstores

- README.md
adding the open ssf badge to the readme https://bestpractices.coreinfrastructure.org/en/projects/6554
Need to merge these PRs before:
> chore(readme): add open ssf badge

- .github/workflows/codeql-analysis.yml
Adding a security scan on our codebase.
Note this is the default one propose by github
> ci: add codeql analysis 

- .pre-commit-config.yaml
> chore: add flake8 to precommit hook

- CONTRIBUTING.md
adding our test policy as required by the open SSF badge
> chore: update contribution

- .gitignore
Add files generated by unit tests to gitignore.
> test: add files generated by unit tests to gitignore.

- docarray/document/mixins/audio.py
atm when calling `load_uri_to_audio_tensor` we open a file but don't close it.
This PR enforce the closing behavior
> fix: the file handler is close properly and wrap into a context manager

- docs/advanced/document-store/elasticsearch.md
- docs/advanced/document-store/index.md
- docs/advanced/document-store/redis.md
- docs/advanced/document-store/weaviate.md
Poor man's fork of https://github.com/jina-ai/docarray/pull/610 so that the CI builds the docs
> docs(array): add section on persistence mutation and context manager

- docarray/math/evaluation.py
- docs/fundamentals/documentarray/evaluation.md
- tests/unit/math/test_evaluation_metrics.py
Goals:
- correct the implementation of R-Precision
- add hints in the documentation about potentially incorrect evaluation scores
- add tests for all metric functions
- add links to developer reference of metric functions in the documentation
> refactor: change r precision calculation and documentation

- docarray/array/mixins/evaluation.py
- docs/fundamentals/documentarray/evaluation.md
- tests/unit/array/mixins/test_eval_class.py
Goals:
- Allow the user to add labels to the documents instead of passing an addtional ground truth `DocumentArray`
> feat: add support for labeled dataset to evaluate function

- docarray/array/document.py
- docarray/array/storage/annlite/backend.py
- docarray/array/storage/annlite/getsetdel.py
- docarray/array/storage/base/getsetdel.py
- docarray/array/storage/elastic/backend.py
- docarray/array/storage/elastic/seqlike.py
- docarray/array/storage/qdrant/backend.py
- docarray/array/storage/sqlite/backend.py
- docarray/array/storage/sqlite/seqlike.py
- docarray/array/storage/weaviate/backend.py
- docarray/array/storage/weaviate/seqlike.py
- docs/advanced/document-store/index.md
- tests/unit/array/test_advance_indexing.py
- tests/unit/array/test_sequence.py
> fix(array): make docarrays sync when explicitly synced and when exiting context manager only

- docarray/array/mixins/io/pushpull.py
Show the error message coming from the server in push, if the code is 403
> feat: show server error message in push

- docarray/array/storage/qdrant/backend.py
- docs/advanced/document-store/qdrant.md
- scripts/docker-compose.yml
- setup.py
- tests/unit/array/docker-compose.yml
Goals:
- ...This PR is aimed to fix the support for qdrant from Docarray
- ...
> fix: support qdrant 0.8

- docarray/array/mixins/evaluation.py
- docs/fundamentals/documentarray/evaluation.md
- tests/unit/array/mixins/test_eval_class.py
Goals:
- allow users to pass multiple metrics to the evaluation function
- calculate all metric scores at once
> feat: multiple metrics in evaluate

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/force-docs-build.yml
- .github/workflows/force-release.yml
- .github/workflows/label-pr.yml
- .github/workflows/tag.yml
Goals:
Adapt to deprecation of github actions features
> ci: fix deprecation of github actions

- docarray/array/document.py
- docarray/array/mixins/io/from_gen.py
- tests/unit/document/test_io.py
Goals:
- Solving this issue: https://github.com/jina-ai/docarray/issues/626
> fix: from csv behaviour

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/force-docs-build.yml
- .github/workflows/force-release.yml
- .github/workflows/label-pr.yml
- .github/workflows/tag.yml
Goals:
Remove deprecation warnings from CI and CD
> ci: update github actions to avoid deprecation warnings

- docarray/array/mixins/io/from_gen.py
- tests/unit/document/test_io.py
Goals:
- Solving this issue: https://github.com/jina-ai/docarray/issues/658
> feat: exception for all from generator calls on instance

- docarray/array/mixins/evaluation.py
- docs/fundamentals/documentarray/evaluation.md
Goals:
- At the beginning of the page, I explain what `evaluate()` does a bit more clearly.
- add documentation for the `metric_names` property
- add documentation on how to implement a custom metric function
- Restructure the docs so that it makes a bit more sense
> docs: complement and rewrite evaluation docs

- docs/fundamentals/documentarray/serialization.md
Signed-off-by: Adrien <adrien.lachaize@gmail.com>
Goals:
- ...
- ...
> Typo "as described"

- setup.py
this PR fix the annlite version to 0.3.13 to avoid breaking change
> fix: patch annlite version

- docarray/__init__.py
Goals:
Bump version to have next `rc` be coherent with past pattern
> chore: bump version

- .github/workflows/force-docs-build.yml
> ci: fix docs building

- .github/workflows/build-old-docs.yml
- .github/workflows/force-docs-build.yml
- .github/workflows/force-release.yml
Goals:
- Fix token check in workflows
Proof that new method works:
- Failed: https://github.com/Jackmin801/JinaDocArrayTest/actions/runs/3321088596
- Succeeded: https://github.com/Jackmin801/JinaDocArrayTest/actions/runs/3321089132
Proof that old method didnt work:
- https://github.com/Jackmin801/JinaDocArrayTest/actions/runs/3318846242/jobs/5483262732
> ci: fix token check

- docs/_templates/sidebar/brand.html
Goals:
- resolves https://github.com/jina-ai/docarray/issues/690
> docs: fix version selector state out of sync when entering on url

- README.md
this pr fix in mistake in the readme
> chore(readme): add rich in the readme

- docarray/array/mixins/io/pushpull.py
- docarray/helper.py
Signed-off-by: Han Xiao <han.xiao@jina.ai>
- move docarray version info into `metaData`
- remove unreachable warning code
> feat: add docarray version to push

- setup.py
unpin rocksdict in test dependencies
> chore: unpin rocksdict in tests

- GOVERNANCE.md
This PR just fix a couple of typos in the governance.md file
> chore: fix type gov

- LICENSE
- README.md
- docs/conf.py
- setup.py
This PR update the trademark of DocArray to the LF AI one
> chore: update trademark to lf ai

- docarray/array/storage/weaviate/backend.py
- docarray/array/storage/weaviate/find.py
- docarray/array/storage/weaviate/getsetdel.py
- docarray/array/storage/weaviate/seqlike.py
- docs/advanced/document-store/weaviate.md
- scripts/docker-compose.yml
- setup.py
- tests/unit/array/docker-compose.yml
- tests/unit/array/mixins/test_find.py
- tests/unit/array/storage/weaviate/test_query_params.py
Based on https://github.com/docarray/docarray/pull/734
Goals:
> feat: update weaviate server to v1.16.0 and client to 3.9.0

- docs/advanced/document-store/weaviate.md
- scripts/docker-compose.yml
- tests/unit/array/docker-compose.yml
Goals: bump minor version of Weaviate
> feat: update weaviate server to v1.16.1

- docarray/array/__init__.py
- docarray/array/mixins/__init__.py
- docarray/document/__init__.py
- docarray/document/mixins/__init__.py
- docarray/predefined_document/__init__.py
- docarray/proto/__init__.py
Normalize and use absolute import everywhere
> refactor: use absolut import everywhere

- docarray/array/mixins/proto.py
- docarray/document/base_node.py
- docarray/document/mixins/proto.py
- docarray/typing/tensor/tensor.py
- docarray/typing/url/any_url.py
renamed `_to_nested_item_protobuf` to `_to_node_protobuf`
> refactor: rename nested

- tests/unit/array/mixins/test_find.py
Assertion should be `r.tags['i']<=5` when filter is not `None`.
> test: fix test find by text and filter

- docarray/array/base.py
- tests/unit/test_pydantic.py
> test: update failing test

- docs/advanced/document-store/benchmark.md
Hope it works this time. All commits signed off from the start.
Goals:
- Improve English in benchmark docs
> docs: fix benchmark english

- docarray/__init__.py
> chore: update docarray version

- docarray/array/__init__.py
- docarray/array/array.py
- tests/units/array/test_mixins/test_attribute.py
> refactor(v2): renamed variable and files

- docs/get-started/what-is.md
Signed-off-by: Joan Fontanals <jfontanalsmartinez@gmail.com>
Goals:
- ...
- ...
> docs: fix broken docs

- .github/workflows/cd.yml
This increases cd timeouts to be the same as the ci timeouts
> ci: align cd timeout with ci timeout

- docs/fundamentals/documentarray/access-attributes.md
Signed-off-by: coolmian <36444522+coolmian@users.noreply.github.com>
Goals:
- ...
- ...
#841
> fix(docs): correction document description

- GOVERNANCE.md
with regard to docarray joining the LF AI foundation we are updating the governance
> chore: update governance

- README.md
> chore(v2): update readme

- README.md
- pyproject.toml
small pr to update for the release of the alpha
> chore(v2): update for release

- .github/workflows/cd.yml
- .github/workflows/publish-docarray-org.yml
- README.md
Signed-off-by: Nan Wang <nan.wang@jina.ai>
Goals:
- The checking for REAME.md should not raise an error in cd. https://github.com/docarray/docarray/actions/runs/3585274283/jobs/6033046903
> ci: fix the wrong error msg

- .github/workflows/cd.yml
- .github/workflows/publish-docarray-org.yml
Goals:
- fix the error in `.github/workflows/publish-docarray-org.yml` which causes this error https://github.com/docarray/docarray/actions/runs/3594725408/jobs/6053362924
> remove error return in ci

- .github/labeler.yml
- .github/workflows/ci_only_pr.yml
since our documentation for v2 is mainly docstring we need to build to documentation on each pr
> chore(v2): run docs building all the time

- README.md
- Remove "cross-modal" references
- All instances of "multi-modal" to multimodal 
- Fix typos
- Change subject to "you" not "one"
- Remove ambiguity in some phrasing
Goals:
- More professional docs
> docs(readme): polish text

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
> chore(v2): update ruff to 0.0.165

- docarray/__init__.py
this pr bump docarray to 0.20.0 for the next minor release
> chore: bump docarray minor version

- docarray/array/array.py
> fix: remove useless method

- docarray/typing/tensor/abstract_tensor.py
> fix(v2): remove useless method

- docs/get-started/what-is.md
Goals:
- remove broken link from documentation
- fix : https://github.com/docarray/docarray/issues/927
> docs: remove broken link

- .github/workflows/cd.yml
- .github/workflows/ci.yml
* bump to python 3.8 for testing
* check import and install on different python version
> chore: add different python version to ci

- docs/advanced/document-store/index.md
docs: link to opensearch docs in sidebar
> docs: link to opensearch docs in sidebar

- docarray/array/abstract_array.py
- docarray/array/array_stacked.py
- docarray/predefined_document/image.py
- docarray/predefined_document/mesh.py
- docarray/predefined_document/point_cloud.py
- docarray/typing/__init__.py
- docarray/typing/tensor/__init__.py
- docarray/typing/tensor/abstract_tensor.py
- docarray/typing/tensor/tensor.py
- docarray/typing/tensor/torch_tensor.py
- docarray/util/find.py
- tests/integrations/document/test_proto.py
- tests/integrations/typing/test_tensor.py
rename `Tensor` to `AnyTensor`
> refactor: rename absrtact to any tensor

- .github/workflows/jekyll-gh-pages.yml
Add documentation custom deployment CI to gh-pages branch
> Add documentation custom deployment CI to gh-pages branch

- docarray/array/array_stacked.py
- tests/units/array/test_stack_mod.py
fix some issue related to nesting, optional and stacked mode
> fix pass tensor types to nested da

- GOVERNANCE.md
this pr udpate the tsc member and the governance
> chore: update gov with tsc menbers

- docarray/helper.py
> ci: hide hubble import

- README.md
- docarray/computation/abstract_comp_backend.py
- docarray/computation/numpy_backend.py
- docarray/computation/torch_backend.py
- docarray/typing/tensor/abstract_tensor.py
- docarray/typing/tensor/ndarray.py
- docarray/typing/tensor/torch_tensor.py
- tests/units/typing/tensor/test_tensor.py
- tests/units/typing/tensor/test_torch_tensor.py
Goals:
- Implements https://github.com/docarray/docarray/issues/871
> feat: allow variable tensor dimension

- pyproject.toml
bump the version for the release
> chore: bump version number 

- README.md
- docarray/__init__.py
small update for the alpha v2 release
> chore: update readme for release

- README.md
- docs/index_init.md
- docs/tutorials/mutlimodal_training_and_serving.md
add a example notebook to showcase DocArray with pytorch and fastapi
> docs: add pytorch training notebook

- docs/get-started/install.md
Goals:
- Consistency
- Grammar
> fix(install docs): consistency, grammar

- README.md
- docarray/__init__.py
- pyproject.toml
> chore: bump version 

- docs/proto/index.md
update documentation to show a warning about proto special behavior with tags
inspired by https://github.com/jina-ai/jina/pull/3349
> docs: add warning proto tag

- .github/workflows/ci.yml
- .github/workflows/ci_only_pr.yml
change when the ci trigger. Goal is that the documentation is built automatically on each push to `feat-rewrite-v2`
> fix: build docs on feat rewrite branch

- .github/workflows/build_docs_on_branch.yml
- .github/workflows/ci_only_pr.yml
- README.md
docs building is failing in ci on `feat-rewrite-v2` this pr fix it
> chore: fix docs building 

- .github/workflows/build_docs_on_branch.yml
- README.md
> fix: update dcs url

- docarray/typing/__init__.py
> fix: add missing import

- docarray/array/array.py
- docarray/array/array_stacked.py
- tests/units/array/test_array.py
- tests/units/array/test_array_stacked.py
Signed-off-by: Joan Fontanals Martinez <joan.martinez@jina.ai>
Goals:
Implement `__del_item__` for DocumentArray and DocumentArrayStacked
> feat: delitem for DocumentArray

- poetry.lock
- pyproject.toml
* update to mypy 1.0
* update ruff to latest
> chore: update mypy and ruff

- docs/get-started/what-is.md
Goals:
Update documentation to reflect future goals.
> docs: remove mention about future support for big data loading

- docarray/base_document/mixins/proto.py
tiny refactor on the from protobuf
> refactor: refactor from proto code

- docarray/array/array.py
- docarray/array/array_stacked.py
We now validate that the data is a correct document, on init, append, extend and insert in a DocumentArray
> feat: add validation on document array

- docarray/typing/tensor/embedding/torch.py
- tests/units/typing/tensor/test_torch_tensor.py
Goals:
This PR is related to #1131
> fix: enable torchembedding deepcopy

- docarray/__init__.py
- pyproject.toml
> fix: fix version num

- .github/workflows/ci.yml
> fix: fix ci

- docs/fundamentals/cloud-support/data-management.md
> docs: fix small typo in pull

- docs/advanced/graphql-support/index.md
- docs/advanced/torch-support/index.md
Goals:
- Tidy up English
- Better comprehension
Should I continue making improvements to the v1 docs? Or just work on v2?
> docs: fixes for graphql, torch pages

- docs/_templates/page.html
- docs/conf.py
> docs: remove docsqa

- CONTRIBUTING.md
- tests/integrations/torch/data/test_torch_dataset.py
> chore: update contributing guideline

- CONTRIBUTING.md
add instruction to add dependency
> chore: update contribution guideline

- README.md
> docs(v2-readme): fix up english

- docarray/display/document_summary.py
Attributes of type int, float and some others are not displayed in a Document's summary:
```python
from docarray import BaseDocument
class MyDoc(BaseDocument):
a: int
b: float
c: str
d: bool
e: complex
f: range
g: dict
h: set
i: frozenset
j: bytes
k: bytearray
l: memoryview
class Config:
arbitrary_types_allowed = True
doc = MyDoc(
a=1,
b=1.0,
c='str',
d=True,
e=1j,
f=range(6),
g={1: 444},
h={3, 4, 5, 6},
i=frozenset({9, 8, 7, 6}),
j=b"Hello",
k=bytearray(5),
l=memoryview(bytes(5))
)
doc.summary()
```
output:
```
📄 MyDoc : f2f8cc7 ...
╭─────────────────┬────────────────────╮
│ Attribute       │ Value              │
├─────────────────┼────────────────────┤
│ c: str          │ str                │
│ g: dict         │ {1: 444}           │
│ h: set          │ {3, 4, 5, 6}       │
│ j: bytes …
```
> fix: add int, float and others to doc summary

- docarray/utils/find.py
Goals:
fixes the docstring example of the `find_batched()` utility function
> docs: fix docstring example of find_batched

- docarray/utils/map.py
- docs/api_references/utils/filter.md
- docs/api_references/utils/find.md
- docs/api_references/utils/maps_docs.md
- docs/api_references/utils/reduce.md
> docs: fix map docstring

- docarray/array/doc_vec/doc_vec.py
Goals:
correction in docstrings
> fix: DocArrayStack to DocVec in docstrings

- README.md
- tests/documentation/test_docs.py
Goals:
Create a nice pretty readme!
> docs: rewrite readme

- docs/api_references/array/any_da.md
- docs/api_references/array/da_stack.md
- docs/glossary.md
- docs/user_guide/representing/array.md
- docs/user_guide/representing/first_step.md
- mkdocs.yml
Add array representing section
> docs: add DocList and DocVec section

- docarray/array/doc_list/io.py
- tests/toydata/books.csv
- tests/units/array/test_array_from_to_csv.py
Goals:
Currently, only local urls work. Let's allow remote ones too
> feat: read from remote csv file

- docarray/array/doc_list/io.py
- tests/units/array/test_array_from_to_pandas.py
rename from_pandas to from_dataframe
> refactor: rename from_pandas to from_dataframe

- docs/how_to/audio2text.md
- docs/how_to/multimodal_training_and_serving.md
- docs/how_to/optimize_performance_with_id_generation.md
- docs/user_guide/intro.md
- docs/user_guide/sending/first_step.md
- docs/user_guide/storing/first_step.md
- mkdocs.yml
Goals:
- Make wording consistent
- FIx English
> docs(menu): consistency, wording fixes

- docarray/index/backends/elastic.py
- tests/index/elastic/fixture.py
- tests/index/elastic/v7/test_index_get_del.py
- tests/index/elastic/v8/test_index_get_del.py
Goals:
This PR is related to issue #1352
> fix: set elastic index default dims to -1

- docarray/array/any_array.py
- docarray/array/doc_list/io.py
- docarray/array/doc_vec/doc_vec.py
- docarray/base_doc/mixins/update.py
- docarray/data/torch_dataset.py
- docarray/typing/tensor/audio/abstract_audio_tensor.py
- docarray/typing/tensor/image/abstract_image_tensor.py
- docarray/typing/tensor/image/image_tensorflow_tensor.py
- docarray/typing/tensor/image/image_torch_tensor.py
- docarray/typing/tensor/video/video_tensor_mixin.py
- docarray/typing/url/url_3d/mesh_url.py
- docarray/typing/url/url_3d/point_cloud_url.py
- docarray/typing/url/video_url.py
Goals:
Added some missing links in the docs, fixxed some docstring renderings, clean up a bit
> docs: add missing links and clean up

- README.md
Goals:
tweak readme wording and add links
> docs: tweak readme wording and add links

- docarray/index/abstract.py
- docarray/index/backends/elastic.py
- docarray/index/backends/hnswlib.py
- docarray/index/backends/qdrant.py
- docarray/index/backends/weaviate.py
- docarray/utils/find.py
- tests/units/util/test_find.py
> refactor: change return type of find batched

- README.md
> fix: fix install

- docarray/index/__init__.py
- docarray/index/backends/qdrant.py
- docarray/index/backends/weaviate.py
- docarray/utils/_internal/misc.py
- Add import checks for weaviate and qdrant
- add `WeaviateDocumentIndex` to `docarray.index.__init__`
> fix: add import checks and add weaviate doc index to index init

- .github/workflows/cd.yml
> fix: add back cd from v1

- .github/workflows/cd.yml
- .github/workflows/ci.yml
wait for all sucess before pushing the pypi
> fix: needs succes all test before pushing to pypi prelease

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- README.md
> chore: fix cd not running

- docarray/array/doc_list/io.py
- docarray/store/jac.py
- tests/integrations/store/test_jac.py
this pr fix the push pull to JAC and make `to_bynary_stream` private
> fix: fix push pull

- tests/integrations/store/test_jac.py
> fix: ingore push pull test

- README.md
Minor changes, biggest is correcting the "woman running" emoji.
> docs: Copy-edit README.md

- pyproject.toml
> chore: bump pyproject version

- .github/workflows/cd.yml
- .github/workflows/force-docs-build.yml
- scripts/get-last-release-note.py
> chore: fix cd docs, readme and release 

- docs/migration_guide.md
Fixing a few small issues I found
> docs(migration-guide): fix issues

- .github/workflows/force-docs-build.yml
hopefully will fix docs action
> chore: use temp file for docs build action

- docarray/utils/_internal/misc.py
> fix: install commands after removing of common

- docarray/array/doc_list/io.py
The binary format of docarray_v2 has been changed in a non-backward-compatiable way. 
In order to tell the difference between docarray_v1 and docarray_v2, a bump in the wire format version is needed.
> fix: binary format version bump

- docarray/index/backends/elastic.py
- docarray/index/backends/hnswlib.py
- docarray/utils/_internal/misc.py
Add install instructions to doc index if hnslib or elastic search is not installed but used.
> feat: add install instructions for hnswlib and elastic doc index

- mkdocs.yml
> feat: add google analytics

- docs/user_guide/storing/docindex.md
Explains how to index predefined documents into a document index
> docs: index predefined documents

- docarray/index/abstract.py
- docs/user_guide/storing/docindex.md
> docs: fix typos

- docs/user_guide/sending/api/fastAPI.md
> docs: fix fastapi

- docarray/index/abstract.py
- tests/index/base_classes/test_base_doc_store.py
> feat: add len into DocIndex

- docarray/index/backends/elastic.py
- fixes [issue 1332](https://github.com/docarray/docarray/issues/1332)
> Add logs to elasticsearch index 

- docarray/index/__init__.py
- docarray/index/backends/helper.py
- docarray/index/backends/hnswlib.py
- docarray/index/backends/in_memory.py
- docs/API_reference/doc_index/backends/in_memory.md
- docs/user_guide/storing/index_in_memory.md
- mkdocs.yml
- tests/index/in_memory/test_in_memory.py
- tests/index/qdrant/fixtures.py
Add an in-memory DocIndex class
> feat: add in-memory doc index

- README.md
- docarray/__init__.py
- pyproject.toml
bump version from 0.30.0 to 0.31.0 for the release
> chore: bump version to 0.31.0

- docarray/array/doc_list/doc_list.py
- docarray/base_doc/doc.py
- tests/units/document/test_base_document.py
THis pr fix the problem of equal between nested DocList
https://github.com/docarray/docarray/issues/1474
> fix: fix equal of BaseDoc with nested DocList

- .github/workflows/cd.yml
- .github/workflows/ci.yml
this pr add secret to the workflow. https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
> chore: ci fix jac by passing secret to workflow

- simple-dl.csv
- simple-dl.json
> chore: remove file

- docs/user_guide/storing/index_qdrant.md
This PR extends the docs with some more Qdrant-related examples, including:
- How to connect to on-premise Docker server
- How to connect to the Qdrant Cloud instance
- How to combine vector search with additional filtering
> Add more Qdrant examples

- docarray/index/backends/hnswlib.py
- docarray/index/backends/in_memory.py
- tests/index/hnswlib/test_find.py
- tests/index/in_memory/test_in_memory.py
This PR is related to issue #1530 .
> fix: add empty judgement to index search

- docarray/index/backends/in_memory.py
- docs/user_guide/storing/index_in_memory.md
- tests/index/in_memory/test_in_memory.py
Closes https://github.com/docarray/docarray/issues/1535
> feat: save and load inmemory index

- docarray/__init__.py
- pyproject.toml
bump version to prepare release
> chore: bump to 0.32.0

- docarray/index/backends/elastic.py
Adding logs sequentially for all indexes in docarray according to [issue](https://github.com/docarray/docarray/issues/1462)
> feat: logs added for es8 index

- docarray/display/document_summary.py
Fixes the summary of Document when List is used. Get the type from annotations better than from the value in `__fields__`
> fix: fix summary of Doc with list

- docarray/typing/tensor/abstract_tensor.py
- docarray/typing/tensor/ndarray.py
- docarray/typing/tensor/tensorflow_tensor.py
- docarray/typing/tensor/torch_tensor.py
- tests/units/typing/tensor/test_tensor_coercion.py
- tests/units/typing/tensor/test_tensor_flow_tensor.py
allow `TorchTensor` to cast from `TensorFlowTensor` and vice versa.
> feat: tensor coersion

- docarray/index/backends/qdrant.py
- tests/index/qdrant/fixtures.py
- tests/index/qdrant/test_external_collection.py
This PR fixes the KeyError thrown when working with external Qdrant collection, as reported in #1630
> fix(qdrant): working with external Qdrant collections #1630

- simple-dl.csv
- simple-dl.json
> chore: remove useless file

- docarray/index/backends/hnswlib.py
> fix: pass limit as integer

- README.md
- docs/user_guide/representing/array.md
This PR integrates improvements for the document based on Han's suggestions from our Discord channel:
1) Typos in the document vector code have been corrected.
2) The text layout has been optimized for better readability.
3) Example code for Fast API has been incorporated to provide more hands-on guidance.
> docs: enhance DocVec section

- docarray/index/abstract.py
- docarray/index/backends/elastic.py
- docarray/index/backends/hnswlib.py
- docarray/index/backends/in_memory.py
- docarray/index/backends/qdrant.py
- docarray/index/backends/redis.py
- docarray/index/backends/weaviate.py
- tests/index/base_classes/test_base_doc_store.py
- tests/index/base_classes/test_configs.py
small refactoring: put contains method in the base class and ask backends to implement _doc_exists
> refactor: contains method in the base class

- tests/documentation/test_docs.py
will fix broken ci and test coverage on main
> fix: fix readme test

- docarray/utils/filter.py
As per suggestion in #1749, Some better documentation about the syntax of the filtering query is required
> docs: improve filtering docstrings

- .github/ISSUE_TEMPLATE/bug-v1-deprecated.yml
- .github/ISSUE_TEMPLATE/bug-v2.yml
> chore: remove pydantic ref from issue template

- docs/user_guide/representing/first_step.md
- tests/units/document/test_any_document.py
there is a small things that users need to be aware of when setting configs, so i am explaining that here.
~~TODO: small test~~ done
> docs: explain how to set document config

- docarray/utils/create_dynamic_doc_class.py
- tests/units/util/test_create_dynamic_code_class.py
Porting fix https://github.com/jina-ai/jina/pull/6035 to docarray
> fix: skip doc attributes in __annotations__ but not in __fields__

- docarray/base_doc/doc.py
- poetry.lock
- pyproject.toml
> feat: add BaseDocWoId

- docarray/array/doc_list/io.py
- docarray/array/doc_vec/io.py
- docarray/base_doc/mixins/io.py
- docarray/store/helpers.py
- docarray/utils/_internal/misc.py
Closes the immediate type issue in https://github.com/docarray/docarray/issues/1670
> feat: use literal in type hints

- docs/API_reference/doc_index/backends/epsilla.md
- docs/user_guide/storing/docindex.md
- docs/user_guide/storing/index_epsilla.md
- mkdocs.yml
This PR adds documentation for EpsillaDocumentIndex.
EpsillaDocumentIndex was merged in https://github.com/docarray/docarray/pull/1835
> docs(epsilla): add epsilla integration guide

- docarray/array/any_array.py
Issue: https://github.com/docarray/docarray/issues/1839
---
I encountered the following issue when using langchain in Python 3.12:
https://github.com/langchain-ai/langchain/issues/15016
```console
return Generic.__class_getitem__.__func__(cls, item)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute '__func__'. Did you mean: '__doc__'?
```
It caused by this PR (https://github.com/docarray/docarray/pull/1147)
```Python
https://learn.deeplearning.ai/langchain/lesson/5/question-and-answer
```
> fix: error type hints in Python3.12 (#1147)

- docarray/index/backends/mongodb_atlas.py
- tests/index/mongo_atlas/__init__.py
We run a nightly CI. We left it failing over the summer. This is a __tiny__ change. Please merge when you can.
> MongoDB Atlas: Two line change to make our CI builds green

- README.md
Commit dbf2bba3c74169e58ef82fa1e3e46f492cab95f7 renamed the license file from `LICENSE` to `LICENSE.md`. This PR adjusts sources to changes.
> fix: update license location
