docarray/docarray

docarray/document/mixins/mesh.py
tests/unit/document/test_converters.py

`deduplicated()` would throw **divide by zero** error in some cases.

fix: improve mesh data loading

---

docarray/array/document.py

An empty DA instance cannot be assigned to a new DA instance, as shown in the following:
```
matches = DocumentArray()
query = Document()
query.matches = matches
```
yields
```
AttributeError: 'DocumentArray' object has no attribute '_id_to_index'
```

fix: id_to_index initialization

---

docarray/array/document.py
docarray/types.py
tests/unit/array/mixins/test_getset.py

Currently setting for example `.text` the attribute for a concrete `Document` in a  `DocumentArray`  results to setting the first character in the string. 
```python
da = DocumentArray([Document(),Document(), Document()])
da[[0,1],'text'] = ['jina','jana']
print(da[:,'text'])
da = DocumentArray([Document(),Document(), Document()])
da[[0],'text'] = 'jina'
print(da[:,'text'])
da = DocumentArray([Document(),Document(), Document()])
da[[0],'id'] = '1234'
print(da[:,'id'])
```
In master 
```
['jina', 'jana', '']
['j', '', '']
['1', 'b6ac7ce073ba11ecbdc7787b8ab3f5de', 'b6ac7d3073ba11ecbdc7787b8ab3f5de']
```
This happens because the setter has …

fix: single doc set in docarray

---

docarray/array/mixins/plot.py

This PR will add an option to `plot_embeddings` to bind embedding-projector server to given host. Setting this option to `0.0.0.0` will make the projector available on local network.

Bind projector server to host

---

docarray/document/pydantic_model.py
tests/unit/test_pydantic.py

attempt to address https://github.com/jina-ai/docarray/issues/72

fix(pydantic): turn on pydantic smart union

---

docarray/document/__init__.py

Removed duplicated `@overload` of `Document.__init__` and added missing `copy` parameter.

fix(document): constructor overload

---

docarray/array/document.py
docarray/array/mixins/delitem.py
docarray/array/mixins/getitem.py
docarray/array/mixins/setitem.py
docarray/array/storage/base/getsetdel.py
docarray/array/storage/memory/getsetdel.py
docarray/array/storage/sqlite/getsetdel.py
docarray/array/storage/sqlite/seqlike.py
docarray/array/storage/weaviate/__init__.py
docarray/array/storage/weaviate/backend.py
docarray/array/storage/weaviate/getsetdel.py
docarray/array/storage/weaviate/seqlike.py
docarray/array/weaviate.py
setup.py
tests/unit/array/conftest.py
tests/unit/array/docker-compose.yml
tests/unit/array/mixins/test_getset.py
tests/unit/array/mixins/test_io.py
tests/unit/array/test_advance_indexing.py
tests/unit/array/test_construct.py
tests/unit/array/test_sequence.py

To better keep track of the TODO items, I have compiled the TODOs from the code into the following summary:
- Investigate into get/set attribute support (e.g. `da[1, ['text', 'id']]`)
- Clarify, Investigate and refactor the current set attribute logic
- Add test coverage for `AllMixin`
- Combine DocumentArray and its meta object into one single schema
- Investigate and use/test base class' `_set_doc_value_pairs`; add test coverage
- Currently, `vectorIndexConfig` is disabled to allow docs with no embeddings to be added. But this needs to change as it also disables vector search functionality.  Will stay tuned and address this in the next step.
- Add match function
This PR incorporated some previous changes from @alaeddine-13  on test setup and also some initial suggestions from @numb3r3. …

feat: storage option

---

docarray/array/pqlite.py
docarray/array/storage/pqlite/__init__.py
docarray/array/storage/pqlite/backend.py
docarray/array/storage/pqlite/getsetdel.py
docarray/array/storage/pqlite/helper.py
docarray/array/storage/pqlite/seqlike.py
setup.py
tests/unit/array/mixins/test_content.py
tests/unit/array/mixins/test_embed.py
tests/unit/array/mixins/test_empty.py
tests/unit/array/mixins/test_getset.py
tests/unit/array/mixins/test_io.py
tests/unit/array/mixins/test_magic.py
tests/unit/array/mixins/test_parallel.py
tests/unit/array/mixins/test_plot.py
tests/unit/array/mixins/test_sample.py
tests/unit/array/mixins/test_text.py
tests/unit/array/test_advance_indexing.py
tests/unit/array/test_construct.py

- use `serilize_config` instead, same as in `DocumentArraySqlite`
- override `__getstate__` and `__setstate__` for supporting pickle
- pass `test_construct.py`

fix pqlite 

---

docarray/array/storage/registry.py
docarray/array/storage/weaviate/backend.py
docarray/array/storage/weaviate/seqlike.py
tests/unit/array/mixins/test_del.py
tests/unit/array/test_construct.py

Align the del/destructor behavior of `DocumentArrayWeaviate` with `DocumentArraySqlite` (delete data only when `self._persist` is `True`, that is when table name/name in provided in `config`).
Also, adding a check to assert `name` provided is capitalized. This is because if `name` is not capitalized, Weaviate will automatically capitalize the name but users may not be aware of this special case.

fix: weaviate da del behavior

---

docarray/array/mixins/io/common.py
docarray/array/mixins/io/csv.py
docarray/array/mixins/io/json.py
docarray/document/generators.py
tests/unit/array/mixins/test_io.py

I am not 100% sure about this PR, so please think about it **carefully**.
In Jina the chatbot example is currently broken in Windows, because the csv dataset cant be read correctly. This file [here]('https://static.jina.ai/chatbot/dataset.csv') .
Reading this file with `DocumentArray.from_csv` will result in this error:
`
File "c:\users\tobias\pycharmprojects\hello_jina\venv\lib\site-packages\docarray\document\generators.py", line 302, in _sample
for i in iterable:
File "C:\Users\tobias\AppData\Local\Programs\Python\Python38\lib\csv.py", line 111, in next
row = next(self.reader)
File "C:\Users\tobias\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't …

fix: use utf-8 encoding for csv reading

---

docarray/array/mixins/delitem.py
docarray/array/mixins/setitem.py
docarray/array/storage/base/backend.py
docarray/array/storage/base/getsetdel.py
docarray/array/storage/base/helper.py
docarray/array/storage/base/seqlike.py
docarray/array/storage/memory/backend.py
docarray/array/storage/memory/getsetdel.py
docarray/array/storage/memory/seqlike.py
docarray/array/storage/pqlite/backend.py
docarray/array/storage/pqlite/getsetdel.py
docarray/array/storage/pqlite/helper.py
docarray/array/storage/pqlite/seqlike.py
docarray/array/storage/sqlite/backend.py
docarray/array/storage/sqlite/getsetdel.py
docarray/array/storage/sqlite/seqlike.py
docarray/array/storage/weaviate/backend.py
docarray/array/storage/weaviate/getsetdel.py
docarray/array/storage/weaviate/seqlike.py
docs/advanced/document-store/extend.md
setup.py
tests/unit/array/mixins/test_io.py
tests/unit/array/test_advance_indexing.py
tests/unit/array/test_base_getsetdel.py
tests/unit/document/test_feature_hashing.py

feat: use list for offset2id
Goal: Have a unified offset2id data structure for all storage backends and pull out the implementation details of all offset-related operations from the implementations of storage backends.
For now, we are relying on python list because all operations that we currently need will be delegated to built in methods of list: There shouldn't be any pure python for loops interacting with offset2ids.
TODOs:
* weaviate: meta schema
* sqlite: use another column
* pqlite: sqlite table

refactor(array): change primary view to dict and 2nd view to list

---

docarray/array/mixins/__init__.py
docarray/array/mixins/find.py
docarray/array/mixins/match.py
docarray/array/storage/pqlite/find.py
docarray/array/storage/weaviate/find.py
docarray/math/distance/__init__.py
tests/unit/array/mixins/test_find.py
tests/unit/array/mixins/test_match.py

**WANING**: To enable the `match` function to work,   the implementation of `find()` needs to allow the query input as `DocumentArray` (since we need to support **exclude_self** parameter).
```
N = 100
D = 8
da = DocumentArray([Document(id=f'{i}', embedding=x) for i, x in zip(range(N), np.random.rand(N, D))])
q = Document(embedding=np.random.random(D))
result = da.find(q, limit=10)
q.match(da, limit=10)
qa = DocumentArray(q)
result = da.find(qa, limit=10)
qa.match(da, limit=10)
qa = DocumentArray([q] * 2, limit=10)
result = da.find(qa, limit=10)
qa.match(da)
qx = np.random.random(D)
result = da.find(qx, limit=10)
qx = np.random.rand(5, D)
result = da.find(qx, limit=10)
```
```
pq_da = DocumentArray(da, storage='pqlite', …
```

feat: integrate match and find function

---

docarray/array/mixins/io/binary.py
docarray/helper.py
docs/fundamentals/documentarray/serialization.md
tests/unit/array/test_from_to_bytes.py
tests/unit/test_helper.py

Now there is the issue that if a `DocumentArray` is stored as binary users need to remember compression and protocol to load it back.
This PR adds this information as extensions in the file.
Example
```python
da = DocumentArray([Document(tensor=np.array([1,2,3])),  Document(tensor=np.array([7,8,9]))])
da.save_binary( 'my_docarray.protobuf.lz4')
```
will save
```bash
my_docarray.protobuf.lz4
```
Thefore,  later on users don't need to recall which `protocol` and `compress` were used. 
Since the information is in the string this PR parses it so that users don't need to pass this info as keyword arguments to `load_binary`. They can simply do:
```python
da.load_binary('my_docarray.protobuf.lz4')
```
This PR solves https://github.com/jina-ai/docarray/issues/128

feat: add compression and protocol in file name

---

docarray/document/mixins/strawberry.py
docarray/document/strawberry_type.py

We need both strawberry `input` and `type` for `DocumentArray`.
Indeed in strawberry [input](https://strawberry.rocks/docs/types/input-types) and [type](https://strawberry.rocks/docs/types/object-types) are two differents concepts (even if from a code perspective they are very similar).
Briefly : 
* `type` is used to select fields in request / response
* ` input` is used  when "posting" a document. (We need it in core because we always rely on posting a da when calling an endpoint)
So core need both definition in `docarray`. Moreover other users working with docarray might need both as well.
Right now we defined `StrawberryDocumentInput` without correlation with `StrawberryDocument`(the type). So some code is repeated. This is normal, both objects and semantically different even if today …

refactor(graphql): strawberry to input

---

docarray/array/mixins/io/binary.py
tests/unit/array/test_from_to_bytes.py

This PR raises `FileNotFoundError` when a file that is not valid is passed as input to `.load_binary`.

fix: correct file not found error

---

docarray/array/mixins/find.py
docarray/array/queryset/__init__.py
docarray/array/queryset/lookup.py
docarray/array/queryset/parser.py
docarray/lookup.py
tests/unit/array/mixins/test_filter.py
tests/unit/array/test_lookup.py
tests/unit/array/test_queryset.py

The example usages code:
```python
from docarray import DocumentArray
docs = DocumentArray.empty(5)
docs[0].text = 'hello'
docs[1].text = 'world'
docs[2].tags['x'] = 0.3
docs[2].tags['y'] = 0.6
docs[3].tags['x'] = 0.8
result = docs.find({'text': {'$eq': 'hello'}})
print(DocumentArray(result).texts)
result = docs.find({'tags__x': {'$gte': 0.5}})
print(DocumentArray(result)[:, 'tags'])
result = docs.find({'$or': {'tags__x': {'$gte': 0.1}, 'tags__y': {'$gte': 0.5}}})
print(DocumentArray(result)[:, 'tags'])
result = docs.find({'tags__x': {'$gte': 0.1, '$lte': 0.5}})
print(DocumentArray(result)[:, 'tags'])
result = docs.find({'$and': {'tags__x': {'$gte': 0.1}, 'tags__y': {'$gte': 0.5}}})
print(DocumentArray(result)[:, 'tags'])
result = docs.find({'text': {'$eq': '{tags__name}'}})
assert …
```

feat: query language supporting filter

---

docarray/array/mixins/find.py
docarray/array/queryset/lookup.py
docarray/array/queryset/parser.py
tests/unit/array/mixins/test_filter.py
tests/unit/array/test_lookup.py
tests/unit/array/test_queryset.py

- `$not` logic ops, e.g., 
`docs.find({'$not': {'tags__x': {'$gte': 0.5}}})`
- `$size` op
`docs.find({'tags': {'$size': 2}})`

feat: add more comparison/logic ops

---

docarray/base.py
docarray/document/__init__.py
docarray/document/data.py
docarray/document/mixins/property.py
docarray/score/__init__.py

Init 300K classes, Py37, MacM1
Before:
```
init empty Python class ...	0.028s
init Doc no content ...	2.251s
init Doc with content ...	3.091s
init Doc with content and embedding ...	3.463s
```
This PR
```
init empty Python class ...	0.029s
init Doc no content ...	1.025s
init Doc with content ...	1.268s
init Doc with content and embedding ...	1.361s
```
---
```python
from docarray import Document
from toytime import TimeContext
class A:
...
with TimeContext('init empty Python class'):
for _ in range(300_000):
A()
with TimeContext('init no Doc content'):
for _ in range(300_000):
Document()
with TimeContext('init with Doc content'):
for _ in range(300_000):
Document(content='hello')
with TimeContext('init with Doc content and embedding'):
for _ in range(300_000):
Document(content='hello', …
```

perf: optimize Document init

---

docarray/document/data.py

In this PR
```python
In [4]: %timeit da = DocumentArray.empty(100_000)
396 ms ± 3.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
In main ( with the last version of `os.urandom(16).hex()`)
```python
In [3]: %timeit da = DocumentArray.empty(100_000)
603 ms ± 7.34 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Note that I don't simply do `hex(random.getrandbits(128))` because this does not warranty that the hex value will be 32 hex long, which would not make it parsable as a UUID. 
This has a very high chance of failing
```python
uuids = [uuid.UUID(hex(random.getrandbits(128))) for i in range(100_000)]
```
whereas this will allways work
```python
uuids = [uuid.UUID(random.getrandbits(128).to_bytes(16, 'big').hex()) for i in range(100_000)]
```
Note: in future …

perf: speedup id construction time

---

docarray/array/chunk.py
docarray/array/match.py
docarray/array/storage/annlite/backend.py
docarray/array/storage/memory/backend.py
docarray/array/storage/memory/getsetdel.py
docarray/array/storage/qdrant/backend.py
docarray/array/storage/sqlite/backend.py
docarray/array/storage/weaviate/backend.py
docarray/array/storage/weaviate/getsetdel.py

`DocumentArray` is `MutableSequence` -> `Sequence` -> `Iterable`.
`iter(da)` is `Generator` -> `Iterator` -> `Iterable`.
`chain(da1, da2)` is both `Iterable` and `Iterator`.
Maybe we only need to check 1 type
```python
from docarray import DocumentArray, Document
from typing import Generator, Iterator, Sequence, Iterable
da = DocumentArray([Document(), Document(), Document()])
print(isinstance(da, DocumentArray))
print(isinstance(da, Sequence))
print(isinstance(da, Iterable))
my_iter = iter(da)
print(isinstance(my_iter, Iterator))
print(isinstance(my_iter, Generator))
from itertools import chain
da1 = DocumentArray([Document()])
da2 = DocumentArray([Document(), Document()])
da = chain(da1, da2)
print(isinstance(da, Iterator))
print(isinstance(da, Iterable))
print(type(da))
```

refactor: simplify da type checking

---

docarray/document/mixins/plot.py
docarray/types/serializers.py

Currently, installing docarray and using it fails because PIL is not installed with the default tag.

fix: fix PIL dependency

---

docarray/array/storage/base/getsetdel.py
docarray/array/storage/memory/backend.py
docarray/array/storage/memory/getsetdel.py
docarray/array/storage/memory/seqlike.py
tests/unit/array/mixins/test_traverse.py
tests/unit/array/test_advance_indexing.py
tests/unit/array/test_base_getsetdel.py
tests/unit/document/test_feature_hashing.py

closes: https://github.com/jina-ai/docarray/issues/209

refactor: use list for DocumentArrayInMemory

---

tests/unit/array/mixins/test_plot.py

fix: qdrant broken pipe error
Before the fix, large image files were implicitly added to the CI which exceeds qdrant's max request size of 32 MB (resulting in `ResponseHandlingException: [Errno 32] Broken pipe`).
Therefore, we fix the path of images to avoid such behavior from happening

fix: qdrant broken pipe error

---

tests/unit/document/test_image.py

This PR is adding two unit tests for the function `_to_image_tensor` in `docarray/document/mixins/image.py`.
--- 
**Note**: I could not find a way to cover lines 340-341: https://github.com/jina-ai/docarray/blob/73f2aef9d3145f4d29982681fc8632230c37fdf4/docarray/document/mixins/image.py#L338-L341
By looking at the internals of `PIL.Image.convert`, it seems like there is no way to read the image correctly at
https://github.com/jina-ai/docarray/blob/73f2aef9d3145f4d29982681fc8632230c37fdf4/docarray/document/mixins/image.py#L333
and then make it fail during the conversion to `RGB`. Could it be a leftover/patch for something weird that happened in the past? If not, how can this be meaningfully tested?

test(image): add unit tests for _to_image_tensor

---

docarray/array/storage/qdrant/backend.py

fix: fix find by vector of n_dim=1

fix: fix find by vector of n_dim=1

---

docarray/array/mixins/io/pushpull.py
tests/unit/array/mixins/test_pushpull.py

Goals:
- Added `public` parameter to `push` method for indicating docarray is public or private.

feat(hubble): add public parameter to da.push

---

docs/fundamentals/dataclass/construct.md

Goals:
- add `Tabular` for the list of all the supported modulities.

docs: add tabular modality into the table

---

docarray/array/storage/sqlite/backend.py
docarray/array/storage/sqlite/seqlike.py
tests/unit/array/test_backend_configuration.py

Extend times in sqlite can be quite high due to length checking (when it is not needed in the batch case for each added item). Thanks @guenthermi for providing the insight!
In master:
```bash
Size: 1       len: 1        init-time: 0.00866 insert-time: 0.00048
Size: 10      len: 10       init-time: 0.00217 insert-time: 0.00359
Size: 100     len: 100      init-time: 0.00226 insert-time: 0.03473
Size: 1000    len: 1000     init-time: 0.00275 insert-time: 0.37138
Size: 10000   len: 10000    init-time: 0.01    insert-time: 3.72639
Size: 100000  len: 100000   init-time: 0.07416 insert-time: 98.56179
```
In this PR:
```bash
Size: 1        len: 1         init-time: 0.01598 insert-time: 0.00047
Size: 10       len: 10        init-time: 0.00203 insert-time: 0.00058
Size: 100      len: 100 …
```

perf[sqlite]: batch update on sqlite extend

---

docs/_templates/page.html

Goals:
Add a template to prevent the qabot slot elements from showing on the docs pages.

fix(qabot): hide the slot elements on the docs page

---

docarray/array/mixins/io/pushpull.py

Goals:
- `api.jina.ai` is unstable sometimes, remove this layer to get better quality. We need to maintain the old domain even we move to new domain anyway, so no worries about writing domain down directly. 
Related to https://github.com/jina-ai/hubble/issues/434

feat(hubble): use fixed domain for hubble api

---

setup.py

Revert "feat: make distance metric configurable in Weaviate backend"

fix: update qdrant to support python 3.7

---

setup.py

recent release in protobuf causes the following problem:
```text
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be 
regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
```
As a quick fix, we fix the protobuf version to less than 4.21
The best solution would be to regenerate proto with protoc >= 3.19.0

fix: fix protobuf dependency

---

docarray/array/mixins/io/pushpull.py
tests/conftest.py
tests/unit/array/mixins/test_pushpull.py

Goals:
- Enable passing Jina authentication token from the environment for `da.push` and `DocumentArray.pull`. Uses key `JINA_AUTH_TOKEN`

feat: load jina auth token from environment

---

tests/unit/array/mixins/test_find.py
tests/unit/array/mixins/test_match.py

Pre-filtering with the operator equal is not working with qdrant backend. See full issue for details https://github.com/jina-ai/docarray/issues/387
To do filtering with with `eq` and `neq` one should use the `match` keyword.
for `eq`:
`filter = {'must': [{'key': 'price', 'match': {'value': 7}}]}`
for `neq`:
filter = {'must_not': [{'key': 'price', 'match': {'value': 7}}]}
This pr fix the test to use this notation for the filter

fix(tests): eq and neq operator for qdrant filtering 

---

docarray/document/mixins/mesh.py
tests/unit/document/test_converters.py

Summary:
This PR convert mesh tensor get from `load_uri_to_point_cloud_tensor` to numpy array.
Description:
We use `Trimesh` APIs in this method and it returns a datatype of `<class 'trimesh.caching.TrackedArray'>` which is a subclass of numpy array ([reference](https://trimsh.org/trimesh.caching.html#trimesh.caching.tracked_array)). This may cause some data type problems in downstream applications.

fix: convert mesh tensor to nparray

---

docs/advanced/document-store/index.md

This PR makes the first context of a document store with an example that shows the context manager. We want to ensure that users see the most important difference between a standard DocumentArray and a DocumentArray with a storage backend **the first time the information is presented in the Documentation**. Otherwise they can stop reading the docs and build code with an example that we don't want them to use.
This month we have had several users with problems that had the root cause in not using the CM when modifying a DocumentArray.

docs: present documentarray modification with context manager

---

docarray/document/mixins/image.py
docarray/document/mixins/plot.py
tests/unit/document/test_converters.py

Long uri makes rich render in notebook extremely slow

fix: skip render long uri

---

docarray/array/storage/elastic/backend.py
docarray/array/storage/elastic/seqlike.py
tests/unit/array/storage/elastic/test_add.py

Goals:
On bulk index submit, if there is error occured ( for example if data type provided is wrong ( in test, I give example by providing int64 data inserted into int32 column )), it will raise BulkIndexError, however the documents is still inserted to the main index but due to error raises, the offset is not updated.
In this PR, I try to fix the issue and also increase the performance by using parallel_bulk and set raise_on_error to False, then return the index error info to the caller
speed benchmark result :
1000 Docs, emb dim = 3, average of 20 runs
with parallel bulk, 4 thread = 15.89 s
with bulk = 21.34 s
- ...
- ...

fix(elastic): inconsistent offset on bulk index error and improve bulk performance

---

docarray/array/mixins/plot.py

For DiscoArt
```python
da.plot_image_sprites(skip_empty=True, show_index=True, keep_aspect_ratio=True)
```

feat(plot): keep aspect ratio

---

README.md

docs: remove the closed discussion link

---

docarray/document/pydantic_model.py
tests/unit/document/test_multi_modal.py

This bug is the root cause of multi-modal documents not working after being (de)serilaized from/to json or dict.
Details here: https://github.com/jina-ai/docarray/issues/429
Better multi-modal support (https://github.com/jina-ai/docarray/pull/425) partially depends on this.
There seems to be no super elegant way of solving this with pydantic, based on [this](https://pydantic-docs.helpmanual.io/usage/models/#private-model-attributes) and [this](https://github.com/samuelcolvin/pydantic/issues/655).
I see two options:
1. make metadata public, so rename `_metadata` -> `metadata`
2. set and validate `_metadata` manually
In order not to change the pydantic model of `Document`, this PR implements option 2.

fix: keep _metadata when serializing to dict and json

---

docarray/document/mixins/multimodal.py
tests/unit/document/test_multi_modal.py

This allows Documents that come from a multimodal dataclass to expose their multimodal attributes like any other 'native' attribute (check last line in the code snippet):
```python
MyText = TypeVar('MyText', bound=str)
def my_setter(value) -> 'Document':
return Document(text=value + ' but custom!')
def my_getter(doc: 'Document'):
return doc.text
@dataclass
class MyMultiModalDoc:
avatar: Image
description: Text
heading: MyText = field(setter=my_setter, getter=my_getter, default='')
m = MyMultiModalDoc(avatar='testflow.jpg', description='hello, world', heading='hello, world')
d = Document(m)
print(d.heading)  # prints a Document with text='hello, world but custom!'
print(d.heading.text)  # prints 'hello, world but custom!'
```
This also extends to use inside of an Executor:
```python
class …
```

feat: allow modalities of multimodal docs to be accessed

---

docarray/document/mixins/multimodal.py
tests/unit/document/test_multi_modal.py

Previously, setting a multi-modal attribute did not set chunks properly. This resulted in only Document level access working, while DocumentArray level access was broken.
This PR fixes this.
The previous tests were not comprehensive enough to catch this flaw. This PR adds tests to that effect.

fix: proper setting of multimodal attributes

---

docarray/document/data.py
tests/unit/array/mixins/test_io.py
tests/unit/array/mixins/test_pushpull.py
tests/unit/document/test_docdata.py

replacing #462 
hi guys, there is a bug in docarray Document.id, it is affected by random.seed() , see the behavior here:
```python
import random
da = DocumentArray()
for _ in range(10):
random.seed(0)
np.random.seed(0)
tensor = ...
da.append(Document(tensor=tensor))
print(da[:, 'id'])
```
then you will find:
```
['e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd', 'e3e70682c2094cac629f6fbed82c07cd']
```
**Expected behavior:**
Doc ID should not be controlled …

fix: use os urandom to generate doc id

---

docarray/array/storage/elastic/backend.py
docarray/array/storage/elastic/seqlike.py
tests/unit/array/storage/elastic/test_add.py
tests/unit/array/storage/elastic/test_del.py

Previous Behavior
When delete operation performed  and error occured it will throw these error 
```bash
2022-08-01T19:48:11.223520457Z self._update_offset2ids_meta()
2022-08-01T19:48:11.223527216Z File "/opt/pysetup/.venv/lib/python3.8/site-packages/docarray/array/storage/elastic/backend.py", line 203, in _update_offset2ids_meta
2022-08-01T19:48:11.223553779Z self._send_requests(requests)
2022-08-01T19:48:11.223567841Z File "/opt/pysetup/.venv/lib/python3.8/site-packages/docarray/array/storage/elastic/backend.py", line 165, in _send_requests
2022-08-01T19:48:11.223575146Z failed_index.append(info['index'])
2022-08-01T19:48:11.223581640Z KeyError: 'index'
```
This because it directly parse `'index'` key from the bulk info inside `_send_requests` function
Goals:
- handle the error info from …

fix(elastic): handle bulk operation error info for another op type

---

docarray/array/mixins/io/pushpull.py
tests/unit/array/mixins/test_pushpull.py

Goals:
When a user logout and login again, the `_get_auth_token` function still returns the old authentification token which is not valid anymore due to the lru_cache.  To prevent this unwanted behavior, I suggest to remove the lru_cache decorator. Moreover, I think the cache is not very useful for the `_get_auth_token` function, since sending a request to hubble is usually much more time-consuming than reading the authentification token.

refactor: remove lru_cache decorator from _get_auth_token

---

docarray/array/storage/elastic/find.py
docs/advanced/document-store/elasticsearch.md
tests/unit/array/storage/elastic/test_find.py

Goals:
- Enable Elastic Search knn search performance tuning by configure `num_candidates` param during `find` method call

feat(elastic): add find kwargs for perf tuning

---

docarray/array/mixins/find.py

```python
d = Document(uri='https://www.gutenberg.org/files/1342/1342-0.txt').load_uri_to_text()
da = DocumentArray(Document(text=s.strip()) for s in d.text.split('\n') if s.strip())
print(da.find('hello'))
```
Before:
```
Traceback (most recent call last):
File "/Users/hanxiao/Documents/jina/toy43.py", line 5, in <module>
print(da.find('hello'))
File "/Users/hanxiao/Documents/docarray/docarray/array/mixins/find.py", line 168, in find
result = self._find_by_text(query, index=index, limit=limit, **kwargs)
TypeError: _find_by_text() got an unexpected keyword argument 'limit'
```
After:
```
Traceback (most recent call last):
File "/Users/hanxiao/Documents/jina/toy43.py", line 5, in <module>
print(da.find('hello'))
File …
```

fix(find): fix misleading signature of _find_by_text

---

docarray/array/storage/base/getsetdel.py

Goals:
make sure that `offset2ids` is correctly updated when deleting in a subindex.
Previously, the call to `del_docs_by_ids()` did not do it, but using `del` does it under the hood.

fix: update offset2id when deleting in subindex

---

docs/advanced/document-store/elasticsearch.md

A user report that a part of the [documentation](https://docarray.jina.ai/advanced/document-store/elasticsearch/#start-elastic-service) was not working. The issue was that the es version that we show in the docs is not up to date.
bump the es version in the docs

docs: bump es version in documentation to match the tests

---

docarray/array/mixins/plot.py

Sometimes `.plot()` can be called when `._subindices` does not yet exist, resulting in an error.
This fix makes a check about the existence of subindices robust against that problem.

fix(plot): be robust against non-existing subindices

---

docarray/array/storage/annlite/getsetdel.py
docarray/array/storage/annlite/helper.py
docarray/array/storage/annlite/seqlike.py

Goals:
-  1. fix the offsetmapping in annlite, (`in_memory=False`)
-  2. `__del__` should be placed in `getsetdel.py`
-  3. should close lmdb cursor in `__del__` so that lmdb can be reused in another annlite instance

fix: annlite offsetmapping

---

docarray/array/storage/sqlite/backend.py

THE `WAL` mode is mush faster then `DELETE` mode for the sqlite.
Goals:
- speed up the sqlite backend

Change journal mode to WAL

---

docs/fundamentals/documentarray/serialization.md

to use serialization one need ton install docarray common. The docs said full which is not needed

docs: push pull use pip install common

---

docarray/document/mixins/plot.py
tests/unit/document/test_summary.py

This pr refactor the code so that we can chose if we want to display from uri or from tensor ( issue https://github.com/jina-ai/docarray/issues/517)
Now you can do
```python
from docarray import Document
d = Document(uri=os.path.join(cur_dir, 'toydata/test.png'))
d.display()
d.display(from_='uri')
d.load_uri_to_image_tensor()
d.uri = None
d.display()
d.display(from_='tensor')
```

feat: allow choose to display from tensor or from uri in document

---

docarray/array/queryset/lookup.py
docarray/document/data.py

speed up the filter case described in https://github.com/jina-ai/docarray/issues/502#issuecomment-1235303756
code:
```python
import time
from docarray import DocumentArray, Document
num = 10_000
da = DocumentArray(Document(text='lsdkfjsl') for x in range(num)) + DocumentArray(Document(blob=b'lsdkfjsl') for x in range(num))
start = time.time()
print(len(da.find(query={'text': {'$exists': True}})))
print(f'time with find: {time.time() - start}')
```
main: 0.24
feat: 0.077
closes: https://github.com/jina-ai/internal-tasks/issues/426

perf: only check if field is set

---

docarray/array/storage/annlite/find.py
setup.py

annlite in 0.3.12, renames private method `_search_documents` which was used by docarray and makes it a public method.
Therefore, we correct the method name in docarray

fix: adapt to annlite changes

---

docarray/array/mixins/io/pushpull.py
tests/unit/array/mixins/test_pushpull.py

Enforce login on `DocumentArray.push/pull` using `hubble.login_required`

feat: login required push pull

---

docarray/document/mixins/blob.py
docarray/document/mixins/helper.py
docarray/document/mixins/image.py
docarray/document/mixins/text.py

Goals:
Capture properly Exceptions from `load_to_uri*` methods and allow to pass extra keyword arguments as `timeout`

feat: allow pass parameters to load_uri_to*

---

docarray/array/storage/redis/backend.py
docs/advanced/document-store/redis.md

closes: https://github.com/jina-ai/docarray/issues/557
Avoid introducing new default values for vector similarity configuration in redis backend, rather use None and leave it up to the database to decide the default value.

fix: keep redis default values for vector similarity parameters

---

docarray/score/data.py
tests/unit/test_named_score.py

Goals:
- Scores with value 0.0 should also be presented in the string representation of NamedScores

fix: remove check of default value in _non_empty_fields

---

docarray/array/storage/base/backend.py
tests/unit/array/test_backend_configuration.py

ATM we could not read from a database which has been setup with sub-indices. This pr fix this (original issue https://github.com/jina-ai/docarray/issues/555 )
```python
from docarray import Document, DocumentArray, dataclass
from docarray.typing import Image, Text
@dataclass
class MyDocument:
image: Image
paragraph: Text
_docs = [(MyDocument( image='https://docarray.jina.ai/_images/apple.png', paragraph='hello world'))]
da = DocumentArray(
storage='sqlite',  # use SQLite as vector database
config={'connection': 'jina4.db', 'table_name': 'test4'},
subindex_configs={'@.[image]': {'connection': 'jina4.db', 'table_name': 'test5'}, '@.[paragraph]': {'connection': 'jina4.db', 'table_name': 'test6'}},  # set up subindices for image and description
)
da.summary()
for item in _docs:
d = …
```

fix: fix load from a database with subindices

---

docs/fundamentals/documentarray/find.md

Goals:
Highlight the fact that query syntax may change depending on DocumentStore used

docs: add note that query syntax is docstore dependant

---

tests/unit/array/mixins/test_getset.py
tests/unit/array/test_sequence.py

Goals:
In tests we are calling `gc.collect` which does not make sense imo

test: remove call to gc collect

---

CONTRIBUTING.md

We want to follow the [OpenSSF best practice](https://bestpractices.coreinfrastructure.org/en/projects/6554), therefore we are adding code style requirement in the contribution guideline

chore: update contribution guideline by adding code style requirement

---

SECURITY.md

OpenSSF badge require a security policy. We have it on jina but not on docarray (https://github.com/jina-ai/jina/blob/master/SECURITY.md)
Add a (smally) modified security policy from the jina one

chore: add securitiy policy

---

docarray/array/storage/annlite/backend.py
docs/advanced/document-store/annlite.md

Goals: Enable loading indexer with PCA in DocumentArray AnnLite backend.
In AnnLite we load the model by their `params_hash` which compute by hashing `n_dim`, `n_components`... 
So in order to successfully load the dumped indexer, we need to pass the `n_components` to AnnLite.
- add a new parameter `n_components`, which is the output dimension of PCA, in `annlite/backend.py` AnnliteConfig

feat: add config for pca in annlite

---

tests/unit/array/mixins/test_plot.py

Disable failing Annlite test: tests/unit/array/mixins/test_plot.py::test_sprite_fail_tensor_success_uri
To be reverted when https://github.com/jina-ai/docarray/pull/622 is merged

chore: disable annlite test

---

docarray/array/storage/qdrant/find.py
docs/advanced/document-store/index.md
docs/advanced/document-store/qdrant.md
tests/unit/array/mixins/test_find.py

Goals:
- Currently the Qdrant backend doesn't support filter, this PR is to support filter method in Qdrant from docarray 
- ...

feat: add filter support for qdrant document store

---

docarray/document/mixins/video.py

Goals:
- Solving this issue: https://github.com/jina-ai/docarray/issues/656
- e.g., timeout: How many seconds to wait for data before giving up, as a float, or a (open timeout, read timeout) tuple.

feat: add args to load_uri_to_video_tensor

---

docs/_templates/sidebar/navigation.html
docs/fundamentals/dataclass/index.md
docs/fundamentals/documentarray/post-external.md
docs/fundamentals/jina-support/index.md

`hub.jina.ai` is moving to `cloud.jina.ai`
This pr change the url eveywhere

chore: move to the new hub url

---

.github/workflows/build-old-docs.yml

Goals:
- Patch issue in failing workflow https://github.com/jina-ai/docarray/actions/runs/3320394868
- The issue is due to it being the first time versioned documentation is being added
- The _versions.json file does not exist yet, so the remove command intended to remove the old _versions.json fails
- A condition was added to the line so that failure to remove the old _versions.json are ignored (since there might not be an old one)

ci: fix first time build issue on build old docs

---

README.md

in the last documentation refine, we embeded three Jupyter notebooks in to finetuner documentation and the image-to-image links being updated.

docs: fix finetuner links in readme

---

docarray/array/storage/redis/find.py
tests/unit/array/mixins/test_match.py

The type of Redis search result score `res.vector_score` is String. This should be converted to `float`.
Goal:

fix(redis): convert score of search results to float

---

docarray/proto/build-proto.sh

fix a typo in the proto building hint

chore: fix hint on building docarray proto

---

docarray/document/mixins/mesh.py
docs/datatypes/mesh/index.md
tests/unit/document/test_converters.py

Goals:
- Currently, DocArray only supports point clouds for 3d data representation. 
- We want to add functions to additionally support 3d data representation of meshes, which include more information about a 3d object than a point cloud, and seem to be more commonly used. Meshes basically consist of a vertices tensor and a faces tensor, which I plan to load to load to chunks, i.e.:
```python
from docarray import Document
doc = Document(uri='some/uri')
doc.load_uri_to_vertices_and_faces_tensors()
```

feat: add 3d data handling of mesh vertices and faces

---

pyproject.toml
setup.py

Goals:
- Get pip to properly pick up this distributions setup requirements
- A similar issue was in jina repo: https://github.com/jina-ai/jina/issues/5346

chore: move setup requirements to pyproject

---

docarray/array/storage/base/getsetdel.py

Currently, any elemental operation of a DA with subindices will attempt to sync the underlying sub indices even though the parent is not synced.
This PR tries to align the behavior and avoid the performance cost of syncing subindices at each operation.

perf: sync sub index only when parent is synced

---

docarray/array/storage/annlite/backend.py
docarray/array/storage/annlite/getsetdel.py
docarray/array/storage/base/getsetdel.py
docarray/array/storage/base/helper.py
docarray/array/storage/elastic/backend.py
docarray/array/storage/elastic/getsetdel.py
docarray/array/storage/elastic/seqlike.py
docarray/array/storage/qdrant/backend.py
docarray/array/storage/qdrant/getsetdel.py
docarray/array/storage/redis/backend.py
docarray/array/storage/redis/getsetdel.py
docarray/array/storage/redis/seqlike.py
docarray/array/storage/sqlite/backend.py
docarray/array/storage/sqlite/getsetdel.py
docarray/array/storage/weaviate/backend.py
docarray/array/storage/weaviate/getsetdel.py
docs/advanced/document-store/index.md
tests/unit/document/test_disable_offset2id.py

Goals:
- ...
- ...DocArray allows list-like behavior by adding offset2id structure to storage backends. This means the database stores, along with documents, meta information about document order.
This information is only updated/synced when a DA is destroyed or quit the context manager. Furthermore, offset2id is updated in memory in all update operations.
However, offset2id is not useful in indexers where concurrent usage is possible and users do not need information about document location. Besides, updating offset2id is not efficient.
Therefore, it's important to have an option that disables list-like behavior (and offset2id with it) and use it in DocumentArray indexers.
```python
@dataclass
class QdrantConfig:
n_dim: int
distance: str = 'cosine'
list_like: bool = True
collection_name: …
```

feat: add flag to disable list-like structure in DocArray

---

.github/workflows/cd.yml
.github/workflows/ci.yml

In #726 we update qdrant version and as qdrant imposes grpcio 1.50.0 which is incompatible with Jina, we make sure to install docarray[full] at the end to respect the jina grpcio version restriction.
However, as we split out tests into proto and old proto tests we didn't respect this.
This PR fixes the order of installation.

ci: impose jina dependencies at the end of CI CD environment setup

---

.github/workflows/cd.yml
.github/workflows/ci.yml

some test (like this one : https://github.com/docarray/docarray/actions/runs/3440631499/jobs/5739320626) Fail because of the time out.
Updating the timeout of the tests in the ci from 30 min to 45 min

chore(ci): update time out of tests

---

docs/datatypes/mesh/index.md

Goals:
Add a link to a Google Colab notebook to demonstrate DocArray's 3d data handling and interactive visualization. Prepare examples for DocArrays point cloud representation as well as vertices and faces representation for users to interact with.

docs: add colab notebook for interactive 3d data visualization

---

docarray/document/document.py

by default pydantic only allow to use types that can be validated. We had to disable it but now that all of our type can be validated (tensor was the last one) it is not needed anymore

feat: only pydantic types

---

CONTRIBUTING.md

Signed-off-by: Sami Jaghouar <sami.jaghouar@jina.ai>
[DCO](https://github.com/apps/dco) is activated on docarray repo.
Therefore this PR add how to pass the DCO app in the contributing guideline

chore: add signed commit to contributing guideline

---

.github/workflows/ci.yml

CI was set to be triggered on pr or in master. But we are working on feat-rewritte-v2 so we need to add this branch for now to the ci check

chore: fix ci not running on refactoring dev branch

---

.github/workflows/ci.yml

the commit lint of the CI is not working on the main/dev branch because it is suppose to work on a PR directly. But we squash merge the PR anyway so the name of the commit does not matter inside the pr branch. So the commit lint is actually never used. This pr just remove it

chore: remove commit lint ci

---

docs/index.md

Signed-off-by: Sami Jaghouar <sami.jaghouar@jina.ai>
Moving Cloud support part of documentation to Integration

docs: move cloud support to integrations

---

docarray/array/abstract_array.py
docarray/array/array.py
docarray/array/mixins/attribute.py
docarray/document/mixins/proto.py
tests/units/array/test_mixins/test_attribute.py

since https://github.com/docarray/docarray/pull/790 we can already do 
```python
from docarray import DocumentArray, Document
class Mmdoc(BaseDocument):
text: str
da = DocumentArray[Mmdoc](
(Mmdoc(text=f'hello') for _ in range(10))
)
assert da.text == 10*['hello']
```
never the less it always return a list of item for the field, even if the field is suppose to contain `Document`. In this case this should return a `DocumentArray` instead of a `List` of `Document`
When the nested field is a Document it returns a `DocumentArray` instead of a `List` of `Document`
```python
from docarray import Text
class Mmdoc(BaseDocument):
text: Text
da = DocumentArray[Mmdoc](
(Mmdoc(text=Text(text='hello')) for _ in range(10))
)
assert da.text == DocumentArray[Text](10*[Text(text='hello'))])
```

feat: allow da bulk access to return da for document

---

docarray/array/mixins/io/pushpull.py
tests/unit/array/mixins/test_pushpull.py

Goals:
- To fix `FileNotFoundError: [Errno 2] No such file or directory: '.../username/test_name'` error when pulling docarray with "username/da-name" formatted name

hotfix: pull docarray with "username/da-name" format

---

docarray/array/storage/annlite/seqlike.py

Signed-off-by: AnneY <evangeline-lun@foxmail.com>
Goals:
Change `extend` of annlite storage backend to private function `_extend`.

fix: change annlite extend to private function

---

docarray/array/mixins/io/pushpull.py
tests/unit/array/mixins/test_pushpull.py

Goals:
- To fix `FileNotFoundError: [Errno 2] No such file or directory: '.../username/test_name'` error when pulling docarray with "username/da-name" formatted name

hotfix: pull docarray with username/da-name format 

---

docarray/document/document.py
docarray/typing/abstract_type.py
docarray/typing/id.py
docarray/typing/tensor/tensor.py
docarray/typing/tensor/torch_tensor.py
docarray/typing/url/any_url.py
docarray/typing/url/image_url.py

Signed-off-by: dong xiang <iamxiangdong@gmail.com>
Goals:
We need to create an common interface via an abstract class for our docarray.typing obj
The abstract class should contain the following methods, 1. _to_node_protobuf (Convert Document into a NodeProto protobuf message). 2. from_protobuf (read value from a proto msg) 3. validate (inherited from pydantic about validating data.)
- ...
- ...

refactor: add typing abstract class

---

README.md
docarray/document/mixins/proto.py
docarray/predefined_document/image.py
docarray/proto/docarray.proto
docarray/proto/pb2/docarray_pb2.py
docarray/typing/__init__.py
docarray/typing/tensor/__init__.py
docarray/typing/tensor/embedding.py
docarray/typing/tensor/ndarray.py
docarray/typing/tensor/tensor.py
tests/integrations/array/test_array_proto.py
tests/integrations/document/test_proto.py
tests/integrations/document/test_to_json.py
tests/integrations/externals/test_fastapi.py
tests/integrations/typing/test_ndarray.py
tests/integrations/typing/test_tensor.py
tests/integrations/typing/test_typing_proto.py
tests/units/array/test_mixins/test_attribute.py
tests/units/document/proto/test_document_proto.py
tests/units/document/proto/test_proto_based_object.py
tests/units/document/test_any_document.py
tests/units/typing/tensor/test_tensor.py

Introduces the type `Tensor` can take any kind of tensor (for now this means np and torch).
The former tensor type is renamed to `NdArray`.
As far as the proto is concerned, `Tensor` does not exist; it is only a shorthand that will cast the input either to `NdArray` or to `TorchTensor`.
closes #782

feat: universal tensor type

---

docarray/array/storage/milvus/getsetdel.py
docarray/array/storage/redis/seqlike.py
tests/unit/document/test_disable_offset2id.py

Signed-off-by: dong xiang <iamxiangdong@gmail.com>
Goals:
- ...
As reported by users, after disabling the list-like flag in Docarray backends, the len should still work, because otherwise the redis backend will fail. Therefore it is necessary to add this functionality.
- ...

fix: add support independent len calculation

---

docarray/array/storage/milvus/backend.py
docarray/array/storage/milvus/find.py
docs/advanced/document-store/extend.md
docs/advanced/document-store/milvus.md
tests/unit/array/storage/milvus/test_milvus.py

Goals:
Milvus: Store distance scores in a `Document`'s `.scores` dictionary, under the key `'score'` to enable accessing those scores.

feat: store distance scores in scores dict

---

tests/unit/array/mixins/test_io.py

Signed-off-by: Johannes Messner <messnerjo@gmail.com>
Removing a failing test case.
Both me and @AnneYang720 were unable to reproduce this error locally, it only seems to fail on the CI.
Besides, loading files straight from disk into a storage backend without creating embeddings first is not a useful scenario anyways.

test: remove faulty test case

---

docarray/typing/__init__.py
docarray/typing/tensor/__init__.py
docarray/typing/tensor/abstract_tensor.py
docarray/typing/tensor/embedding.py
docarray/typing/tensor/torch_tensor.py
tests/integrations/document/test_proto.py
tests/integrations/typing/test_embedding.py
tests/integrations/typing/test_torch_tensor.py
tests/integrations/typing/test_typing_proto.py
tests/units/typing/tensor/test_tensor.py
tests/units/typing/tensor/test_torch_tensor.py

Proper embedding type that allows only 1d tensors:
```python
class MyDoc(Document):
emb1: TorchEmbedding  # ok
emb2: TorchEmbedding[128]  # ok
emb3: TorchEmbedding[3, 224, 224]  # not ok, fails
```

feat: embedding type

---

docarray/array/storage/base/seqlike.py
docarray/array/storage/milvus/seqlike.py
docs/advanced/document-store/extend.md

Implement len (somewhat) natively for milvus, not retlying on offset2id.
Milvus has no real native way to get the number of entities in a collection, so we have to send a full-on general filter query with an expression that always evaluates to true, and then count the returns. Therefore this is only done if list-like is turned off.

fix: native milvus len

---

docarray/array/mixins/plot.py
docs/fundamentals/documentarray/visualization.md

Add the option to exclude additional fields from csv metadata file, such as `.chunks` by adding the parameter `exclude_fields_metas` to `.plot_embedding`.

feat: add exclude fields metas parameter

---

pyproject.toml
tests/units/typing/url/test_image_url.py

the goal of this pr is to mark some test are slow and mark which test require internet.
On my laptop test time is 8 sec and 1.7 without the slow test

chore(v2): add pytest mark slow to tests

---

docarray/typing/tensor/abstract_tensor.py
docarray/typing/tensor/embedding.py
docarray/typing/tensor/ndarray.py
docarray/typing/tensor/torch_tensor.py

Our tensor type is built on top of torch tensor and numpy array. We inherit from both of this class and we add some custom prive function like `__validate_shape__` since that in a future we want to extend the tensor types to jax and tensorflow the likelihood that our custom private method clash with other framework private method increase. Therefore in this PR we rename all of the private method to `__docarray_XXX__`

refactor(v2):  add namespace docarray to tensor private method

---

docarray/array/mixins/setitem.py
docarray/array/storage/base/seqlike.py

Signed-off-by: AnneY <evangeline-lun@foxmail.com>
Goals:
Serialized DocumentArray from old version may not have the attribute `_is_subindex` set. This PR enable backwards compatibility for `_is_subindex`.

fix: backwards compatibility for _is_subindex

---

docarray/array/storage/milvus/backend.py

Goals:
Create a new connection everytime `_init_storage()` is called from Milvus Document Storage.

fix: add multiple connections to milvus

---

docarray/typing/tensor/abstract_tensor.py
tests/units/typing/tensor/test_torch_tensor.py

Goals:
The parameterized tensor type is currently not correctly displayed
```python
from docarray import Document
from docarray.typing import TorchTensor
import torch
class MyDoc(Document):
image_tensor: TorchTensor[3, 224, 224]
tensor: TorchTensor
doc = MyDoc(tensor=torch.zeros(3, 224 ,224), image_tensor=torch.zeros(3, 224, 224))
print(doc.tensor[0][0][0])
print(doc.image_tensor[0][0][0])
>>>TorchTensor(0.)
>>> _ParametrizedTensor(0.)
```
Instead of `_ParametrizedTensor(0.)` we want it to print `TorchTensor[3, 224, 224](0.)`

fix(v2): parameterized tensor display

---

docarray/array/storage/elastic/backend.py

Currently, when `list_like` is set to False, list-like operation is disabled but the offset2id elastic index still being created
Goals:
- handle offset2id index creation when list_like set to false
- ...

fix: remove offset index create on list like false elasticsearch

---

docs/datatypes/index.md
docs/index.md

Anyone got any objections to me changing "Multimodal Data" to "Data Types"?
Rationale: Most people working with DocArray are just working with one data type (as reflected in Google Analytics page/user views). Also we have "Multi-modal" under "Multimodal data" which seems odd.
I know we want to blow the multimodal trumpet, but I think it'd be good to get users building with DocArray for their single-data-types first then converting them to the cause.
- docs(index): fix developer reference(s) typo
- docs(datatypes): change page title to data types

docs: multimodal to datatypes

---

docarray/array/mixins/evaluation.py
tests/unit/array/mixins/oldproto/test_eval_class.py

Goals:
- The `num_relevant_documents_per_label` is calculated in the `embed_and_evaluate` method on the documents in `self`. However, this is only correct if `self` is matched against itself. Instead it should be calculated on the `index_data` attribute if it is provided.

fix: calculate relevant docs on index instead of queries

---

.github/workflows/jekyll-gh-pages.yml

This PR configures a custom github actions to deploy github pages documentation, in order to increase timeout

ci: increase docs deploy timeout

---

docarray/array/mixins/io/csv.py

If a Documents fields contain '\n' this messes up the display in `.plot_embeddings()`. 
Therefore we want to replace all '\n' with whitespaces for display.
E.g. for the following Document:
The information of that Document looks like this:
But should look like this:

fix: replace newline with whitespace to fix display in plot embeddings

---

docarray/array/array.py
tests/units/array/test_array.py

There is currently a bug in v2 when using slice.
`da[0:10]` return a list instead of a DocumentArray
fix the behavior and return a DocumentArray

fix(v2): handle properly slice in getitem  da

---

docarray/array/abstract_array.py

atm doing 
```python
DocumentArray[Image](batch).stack()
>>> <docarray.array.abstract_array.DocumentArray[Image] at 0x7f0952aab040>
```
but it is a DocumentArrayStacked
this pr fix the __name__ of the class so that it is printed
```python
>>> <docarray.array.abstract_array.DocumentArrayStacked[Image] at 0x7f0952aab040>
```

Fix proper name da stacked

---

docarray/array/array.py
docarray/array/array_stacked.py
docarray/document/abstract_document.py
docarray/document/any_document.py
docarray/document/document.py
docarray/document/mixins/proto.py
docarray/util/find.py
tests/integrations/typing/test_typing_proto.py
tests/units/array/test_stack_mod.py

there is a bug with not class object in document atm : 
```python
class MyDoc(BaseDocument):
my_dict: Dict[str, int]
DocumentArray[MyDoc]([MyDoc(my_dict={'a': 1, 'b': 2}) for _ in range(10)]).stack()
```
```
File ~/Documents/workspace/Jina/docarray2/docarray/docarray/array/array_stacked.py:91, in DocumentArrayStacked._create_columns(cls, docs, tensor_type)
88         columns_fields.append(field_name)
89 else:
90     is_torch_subclass = (
---> 91         issubclass(field_type, torch.Tensor) if torch_imported else False
92     )
94     if (
95         is_torch_subclass
96         or issubclass(field_type, BaseDocument)
97         or issubclass(field_type, NdArray)
98     ):
99         columns_fields.append(field_name)
TypeError: …
```

fix: allow dict to be pass in a da stacked

---

docarray/document/mixins/mesh.py
docarray/document/mixins/plot.py
docs/datatypes/mesh/index.md
tests/unit/document/test_converters.py

Fix code snippet for point cloud display with color:
Add `PointCloudEnum.COLORS` as name tag instead of `'point_cloud_colors'`

fix: value extraction of point cloud colors enum in display

---

README.md

Signed-off-by: Johannes Messner <messnerjo@gmail.com>
Goals:
Link our discord in the readme

docs: add discord to the readme

---

docarray/array/array_stacked.py

To give some context, when a DocumentArray enter in stacked mode the tensor data from each document is moved to the column and the document does not own the data anymore. 
What we were doing before this PR was to put None (or even recently to even delete the attribute) inside each document attributes data that has been moved to the DocumentArrayStacked columns, and only when accessing the DA stacked we were putting a view of the column in the data.
This cause several problems: this might lead to thread problem because we don't currently have any-lock to prevent access to the undefined data (still in the column but not in the document as a view) and the `stack` operation let the DocumentArray in a very weird state where it cannot …

refactor: better management of stack mod

---

docarray/array/array.py
docarray/array/array_stacked.py
docarray/computation/abstract_comp_backend.py
docarray/computation/numpy_backend.py
docarray/computation/torch_backend.py
docarray/typing/tensor/abstract_tensor.py
tests/units/array/test_array_stacked.py
tests/units/computation_backends/numpy_backend/test_basics.py
tests/units/computation_backends/torch_backend/test_basics.py
tests/units/util/test_typing.py

We recently introduced some refactoring on DocumentArrayStacked : https://github.com/docarray/docarray/pull/1008 which change a little bit the way we handled the stacking (We removed any state where the document does not hold the data but instead some time its hold a view of the data that has been moved to the column)
As noticed by @JohannesMessner this new way of stacking could be optimized because once the data has been stacked we re traverse the DocumentArray to put the view from the column to the document.
_Originally posted by @samsja in https://github.com/docarray/docarray/pull/1008#discussion_r1067114135_ there is room for improvements. 
We could:
* pre-allocate the data for the tensor column (we can predict the shape and the type by looking at the first row of the da)
* when …

refactor: optimization on stacking

---

docarray/array/array_stacked.py

https://github.com/docarray/docarray/pull/996 introduced the `da.to('cuda')` on `DocumentArrayStacked` like pytorch.
Nevertheless to even stick more with what pytorch is doing we should return self in `to`

fix: return self in to device

---

docarray/document/mixins/multimodal.py
tests/unit/document/test_multi_modal.py

Goals:
If we create a `Document` instance from a `dataclass` instance, all  attributes are gonna be stored in their own Documents in the chunks. If one of the attributes is an iterable, such as a `List[Images]`, we want to be able to access this `DocumentArray` as such. If it is of length 1 though, when accesing the images, we get only one `Document` instead of a `DocumentArrray` of length 1.
To change this behaviour we need to check if the initial attribute type was an iterable, in which case return a DocumentArray. 
```python
from docarray import Document, dataclass
from docarray.typing import Text, Image
from typing import List
@dataclass
class MyDoc:
title: Text
images: List[Image]
doc1 = MyDoc(title='doc 1', images=[
'https://bkimg.cdn.bcebos.com/pic/359b033b5bb5c9ea15ce3757e86fa1003a …
```

fix: doc from dataclass with list

---

docarray/array/array_stacked.py
docarray/typing/tensor/abstract_tensor.py
docarray/typing/tensor/embedding/embedding_mixin.py
docarray/typing/tensor/ndarray.py
docarray/typing/tensor/torch_tensor.py
docarray/utils/find.py
tests/units/document/proto/test_proto_based_object.py

rename all `__docarray_meth__` to `_docarray_meth`

refactor: renamed docarray private method

---

README.md

`:arrow_up:` renders as :arrow_up: on GitHub's markdown rendering, but seems whatever renders the emoji on docarray.org doesn't support `:foo:` emojis.
This fix uses the emoji directly, not the `:foo:` notation.
It should look no different on GitHub (I tested with their rendering engine - looks fine), but should display well on docarray.org

fix: up arrow emoji display in readme on docarray.org

---

docarray/array/array_stacked.py
docarray/computation/abstract_comp_backend.py
docarray/computation/numpy_backend.py
docarray/computation/torch_backend.py
docarray/typing/tensor/abstract_tensor.py
docarray/typing/tensor/ndarray.py
docarray/typing/tensor/torch_tensor.py

Because of some type problem we need multiples times in the codebase to duplicate function definition in the Computional Backend part.
This PR fix this by doing a refactoring on the type part. The new one is less precise and correct that before but more flexible and easier to maintain.
Main difference are two folds:
* Use Instance instead of class in get_comp_backend (to fix the static method pb)
* The return type of the function in the computational backend is always np.ndarray or torch.Tensor. Therefore mypy cannot now that if you passed a TorchTensor (from us) the method will return a TorchTensor. This is a limitation but it allow us to remove the second TypeVar Generic in the Computational backend. This means in some case we need either to tell mypy we know the return type will be a …

refactor: comp backend 

---

docs/tutorials/mutlimodal_training_and_serving.md

- `line.split(",")` does not take into account cases where there are commas in the caption
- the copy in getitem isnt deep, causing a memory leak
- The maximum token length of captions in flickr8k is 43. Padding up to 512 wastes a lot of VRAM which could be used to increase the batch size for more stable training.

fix: fix csv string parsing and memory leak in dataset

---

docarray/array/array.py
tests/units/array/test_array.py

allow to do 
```python
da = DocumentArray()
```
before you had to do 
```python
da = DocumentArray([])
```

feat: add default value to docs in da init

---

docarray/typing/tensor/abstract_tensor.py
docarray/typing/tensor/ndarray.py
docarray/typing/tensor/torch_tensor.py
tests/units/typing/tensor/test_cross_backend.py
tests/units/typing/tensor/test_np_ops.py
tests/units/typing/tensor/test_tensor.py
tests/units/typing/tensor/test_torch_ops.py
tests/units/typing/tensor/test_torch_tensor.py

This is because parametrizing them can cause them to be wrong when operations are performed.
We only need the parametrization during instantiation for validation.
After that, we make no guarantees about the shape.
Goals:
- Addresses #994 
- Doesnt seem like it is mentioned in the docs. Not sure if its relevant to add a section about this

refactor: instances of parametrized tensors are no longer parametrized

---

docarray/documents/audio.py
docarray/documents/image.py
docarray/documents/mesh.py
docarray/documents/point_cloud.py
docarray/documents/text.py
docarray/documents/video.py
tests/integrations/predefined_document/test_audio.py
tests/integrations/predefined_document/test_image.py
tests/integrations/predefined_document/test_mesh.py
tests/integrations/predefined_document/test_point_cloud.py
tests/integrations/predefined_document/test_text.py
tests/integrations/predefined_document/test_video.py

Follow up on this : https://github.com/orgs/docarray/projects/4?pane=issue&itemId=18966242
```python
class MyDoc(BaseDocument):
text1: Text
text2: Text
MyDoc(text1='hello', text2=Text(text='world'))
```
allow to pass directly a Text

feat: add validate function to documents to have less verbose api

---

docarray/documents/text.py
tests/units/document/test_docs_operators.py
tests/units/document/test_text_document.py

Goals:
Solves #1056 
Allows to have a less-verbose `Text` initalization:
```python
from docarray.documents import Text
Text('hello world')
``` 
works

feat: init text directly

---

.github/workflows/ci.yml
pyproject.toml

* remove the dependency cap from poetry
* add CI to test code against latest code version but does not block ci
justification here https://iscinumpy.dev/post/bound-version-constraints/

chore: uncap dependency

---

docarray/array/array.py
docarray/array/array_stacked.py
tests/units/array/test_array_stacked.py

Signed-off-by: Joan Fontanals Martinez [joan.martinez@jina.ai](mailto:joan.martinez@jina.ai)
Goals:
Allow `DocumentArrayStacked` to be created from `Iterable` of `Docs`

feat: allow building DocumentArrayStacked from Iterable of Docs

---

tests/units/document/proto/test_document_proto.py

Signed-off-by: Joan Fontanals Martinez <joan.martinez@jina.ai>
Goals:
Test that serialization respects tensor dtype

test: add tests tensor dtype serialization

---

CONTRIBUTING.md
GOVERNANCE.md
README.md
docarray/array/mixins/traverse.py
docarray/array/storage/qdrant/find.py
docarray/proto/build-proto.sh
docs/advanced/document-store/benchmark.md
docs/conf.py
docs/fundamentals/dataclass/access.md
docs/fundamentals/dataclass/construct.md
docs/fundamentals/dataclass/index.md
docs/fundamentals/document/construct.md
docs/fundamentals/documentarray/subindex.md
docs/html_extra/robots.txt
scripts/docstrings_lint.sh
setup.py
tests/unit/array/mixins/test_pushpull.py

WIP. Replacing all occurrences of docarray.jina.ai with docs.docarray.org
Goals:
- ...
- ...

docs: fix urls to docs.docarray.org

---

docarray/display/document_summary.py
docarray/display/tensor_display.py

Use min width in the rich display instead of a set width, so that the table adjusts more to the data.
This:
Instead of this:

fix(v2): rich display min width instead of set width

---

docarray/computation/tensorflow_backend.py
docarray/display/tensor_display.py

Goals:
Fix tensor summary display from this:
to this:
So, add dtype display, display the tensors class name instead of this '< ... >' and adjust the width if tensor is not displayed by those blocks.

fix: tensor summary 

---

docarray/display/document_array_summary.py

Goals:
Small fix: convert tensor first to numpy, then check for nans, becase `comp_be.isnan(val)).all()` does not work for `TensorFlowTensor`.

fix: da summary tf tensor nan

---

docarray/array/stacked/array_stacked.py
tests/units/array/test_array_stacked.py
tests/units/array/test_array_stacked_tf.py
tests/units/typing/tensor/test_torch_tensor.py

we don't need the setitem when calling `da[0]` anymore. This is because we store the tensor in the document as a view of the column

fix: remove setetiem in getiem

---

docarray/array/abstract_array.py
docarray/utils/filter.py
docarray/utils/query_language/lookup.py
docarray/utils/query_language/query_parser.py
tests/units/array/test_traverse.py
tests/units/util/query_language/test_lookup.py
tests/units/util/test_filter.py

Goals:
Change all seperators in access paths from `.` to `__`
This affects:
- `.traverse()`
- `filter`, `lookup`, `queryparser`: Here, previously `.` was used as acceas path separator and the `__` was used to separate path an operator:  `{access.path}__{operator}`. 
This I wanted to change to: `{access__path}.{operator}`

refactor(v2): change access path separator from `.` to `__`

---

docarray/typing/url/url_3d/mesh_url.py
docarray/typing/url/url_3d/point_cloud_url.py
docarray/typing/url/url_3d/url_3d.py

Goals:
Add argument that are allowed by trimesh to Url3D.load(), such as skip_materials=True to skip the materials and textures during loading, to safe time.

feat(v2): add trimesh load args for `Url3D.load()`

---

poetry.lock
pyproject.toml

Goals:
- this is a change in poetry package install to make sure pytest version should be greater or equal to 7.0
- To fix issue #942 
- Before
- After

fix: bump pytest version to avoid warning issue #942

---

docarray/documents/helper.py
tests/integrations/document/test_document.py

Goals:
This PR is for issue #1152 
In the issue, [Pydantic's create_model](https://docs.pydantic.dev/usage/models/#dynamic-model-creation) was mentioned. In order for the function to return a subclass of `BaseDocument`, we need to pass the parameter `__base__`.

feat: dynamic class creation

---

docarray/typing/url/audio_url.py
docarray/typing/url/image_url.py
docarray/typing/url/url_3d/url_3d.py
docarray/typing/url/video_url.py

Should fix #1195 
Changed `np.ndarray` to `str` in validation methods of URL types

Fix: replaced ndarray with str

---

docarray/doc_index/abstract_doc_index.py
docs/tutorials/add_doc_index.md
tests/doc_index/base_classes/test_base_doc_store.py

Goals:
Give an additional helper method to the Document Index implementer.
Before this PR, we would help the `_index()` implementation by flattening and parsing incoming docs into all columns.
But some backends (e.g. ES) do their bulk indexing by row, not by column.
So this helper creates a generator that "transposes" the data from a column-wise view to a row-wise view

feat: helper method to transpose data

---

docs/advanced/document-store/opensearch.md

docs: fix opensearch docker compose yaml file
Basicallym the used network name should match the one defined

docs: fix opensearch docker compose yaml file

---

docarray/typing/tensor/abstract_tensor.py
docarray/typing/tensor/ndarray.py
docarray/typing/tensor/tensorflow_tensor.py
docarray/typing/tensor/torch_tensor.py
tests/units/typing/tensor/test_tensor.py
tests/units/typing/tensor/test_tensor_flow_tensor.py

Introduces the first feature proposed here https://github.com/docarray/docarray/issues/1185
**Generic behavior for tensor shapes**
It's now possible to use ellipsis when defining tensor shapes. 
Example:
```python
def fn(batch: NdArray[100, ...])
```
which means `batch` is expected to have first dimension of size 100, and can have other arbitrary dimensions which won't be checked while validating the shape.
Other examples:
```python
def fn(batch: NdArray[..., 100]):
pass
def fn(batch: NdArray[3, ..., 100]):
pass
```
**How it works**
If ellipsis is detected in the shape, remove it, and replace by the amount independent variables needed to make the number of dimensions equal for the actual shape and the shape definition. Then, proceed to check if the two shapes are compatible.

feat: ellipsis in tensor shape definition

---

.pre-commit-config.yaml
docarray/doc_index/abstract_doc_index.py
docarray/doc_index/backends/hnswlib_doc_index.py

Goals:
- this PR closes https://github.com/docarray/docarray/issues/1243 by making default search_field to empty string
- this PR updates iSort version because I had issues with current version when checking recommit hooks
-

make default search field empty string

---

docs/tutorials/add_doc_index.md

Goals:
Explain how Document Index implementers should handle the `.id` field when indexing

docs: add explanation about id field

---

docarray/documents/text.py
docarray/documents/video.py

There is a bug related to the type of the `bytes` field in the predefined Documents, such as TextDoc.
The bytes field is of type `Optional[bytes]`, but when looking at `TextDoc.__fields__['bytes'].type_` it equals 'None' instead of `Optional[bytes]`
Because of this, the following fails:
```python
from docarray import DocumentArray
from docarray.documents import TextDoc, VideoDoc
da = DocumentArray[TextDoc]([TextDoc()])
for name, value in TextDoc.__fields__.items():
print(f"name, type = {name, value.type_}")
da.summary()  # fails
da = DocumentArray[VideoDoc]([VideoDoc()])
da.summary()  # fails
```
```
name, type = ('id', <class 'docarray.typing.id.ID'>)
name, type = ('text', <class 'str'>)
name, type = ('url', <class 'docarray.typing.url.text_url.TextUrl'>)
name, type = ('embedding', …
```

fix: bytes type in `TextDoc` and `VideoDoc`

---

docarray/array/abstract_array.py
docarray/array/array/array.py
docarray/array/stacked/array_stacked.py
docarray/data/torch_dataset.py
tests/units/array/stack/test_array_stacked.py
tests/units/array/stack/test_array_stacked_tf.py
tests/units/array/test_indexing.py

This pr removes the `tensor_type` argument from `DocumentArray` init and put it rather at the `da.stack(tensor_type=TorchTensor)` level.
Indeed this argument is only relevant for `DocumentArrayStacked` and was used inside `DocumentArray` only when the stack method was called

refactor(da): remove tensor type from `DocumentArray` init

---

docarray/display/document_summary.py

dict and set attributes are not displayed correctly:
```python
from docarray import BaseDocument
class MyDoc(BaseDocument):
a: dict
b: set
doc = MyDoc(
a={'hello': (1, 0), 'hello1': (1, 0), 'hello2': (1, 0), 'hello3': (1, 0)},
b={'hi', 'ok', 'bye'}
)
doc.summary()
```
output:
```
📄 MyDoc : f1bfd74 ...
```
expected:
```
📄 MyDoc : 38f8628 ...
╭───────────┬──────────────────────────────────────────────────────────────────╮
│ Attribute │ Value                                                            │
├───────────┼──────────────────────────────────────────────────────────────────┤
│ a: dict   │ {'hello': (1, 0), 'hello1': (1, 0), 'hello2': (1,  ... }         │
│           │ (length: 4)                                                      │
│ b: set    │ {'bye', 'hi', 'ok'} …
```

fix: doc summary for dict and set attributes

---

docarray/base_document/mixins/io.py
docarray/proto/__init__.py
docarray/proto/docarray.proto
docarray/proto/pb/docarray_pb2.py
docarray/proto/pb2/docarray_pb2.py
tests/units/document/proto/test_document_proto.py

mainly fix https://github.com/docarray/docarray/issues/1275
```python
from docarray import BaseDocument
class InputSchema(BaseDocument):
data: Dict
doc = InputSchema(data = {'data': (torch.zeros(1), 2)})
doc2 = MyDoc.from_protobuf(doc.to_protobuf())
```
This make this work by using a list of node proto instead of the predefined list of Protobuf

fix: proto ser and deser for nested tuple/dict/list

---

docarray/documents/helper.py
tests/integrations/document/test_document.py

Dynamically create model by guessing types based on an example data given as a dictionary of fields to their corresponding values.
```python
from docarray.documents import ImageDoc
from docarray.documents.helper import create_from_dict
data_dict = {'image': ImageDoc(tensor=np.random.rand(3, 224, 224)), 'author': 'me'}
MyDoc = create_doc_from_dict(model_name='MyDoc', data_dict=data_dict)
doc = MyDoc(image=ImageDoc(tensor=np.random.rand(3, 224, 224)), author='jina')
```
Notes:
1. We don't allow passing an empty dict because what's the point then
2. In case the dict contains None value, we treat corresponding field as type Any
3. Had to disable mypy for the return statement otherwise was throwing weird errors (something with kwargs)

feat: create documents from dict

---

.github/workflows/ci.yml
docarray/index/abstract.py
docarray/index/backends/hnswlib.py
docarray/utils/_typing.py
tests/index/hnswlib/test_find.py
tests/index/hnswlib/test_index_get_del.py
tests/index/hnswlib/test_persist_data.py

Goals:
This fixes the following things in HNSWLibIndex:

fix: hnswlib doc index

---

tests/units/computation_backends/torch_backend/test_basics.py

basic tests addition for torch computational backend

---

docarray/typing/tensor/image/abstract_image_tensor.py
tests/units/typing/tensor/test_image_tensor.py

Goals:
Save an image tensor to file, such as `.jpg` or `.png`

feat: save image tensor to file

---

tests/integrations/doc_index/elastic/fixture.py

fix es test that were not run bc of pytest mark typo

fix: fix type in es test

---

docarray/index/abstract.py
docarray/utils/find.py
tests/index/hnswlib/test_configurations.py
tests/units/util/test_find.py

This does 3 things:
- align naming: `embedding_field` in the `find()` function is renamed to `search_field`, to align with document indexes
- the default of `search_field` is changed to `''` everywhere. We want people to be conscious about their schemas
- remove a warning that is a bit too aggressive, and move it into the docstring

refactor: remove warning, align naming

---

README.md

The markdown was not rendered in the collapsible box before.

docs: fix style in collapsible box

---

docs/user_guide/storing/first_step.md
docs/user_guide/storing/first_steps.md
docs/user_guide/storing/index_elastic.md

- `Overview` to `Introduction` throughout
- Fix `ElasticSearch` to `Elasticsearch`

docs: consistent wording

---

docs/data_types/video/video.md
mkdocs.yml

Resolving the following issues mentioned by @alexcg1:
- data_types/image/image/ - some local URLs need to be to class names, not HTML pages
- data_types/image/audio/ - some local URLs need to be to class names, not HTML pages
- data_types/image/video/ - some local URLs need to be to class names, not HTML pages
**===>** as for the local urls, I used those for `ImageTensor`, `AudioTensor`, `AnyTensor` etc. I linked to the corresponding docs typing section, because they don't show up correctly in the `API reference` section. Will leave it like this for now.
- data_types/video/video/ - video file plays with audio - very distracting
**===>** fixed: muted loop autoplay
- 3d - huge lumps of nasty code for rendering meshes. can we do iframes instead?
**===>** I am not getting this to work while …

docs: clean up data types section

---

docarray/index/backends/hnswlib.py
tests/index/hnswlib/test_persist_data.py

This PR is related to issue #1351 
The issue is that using two time the same `work_dir` lead to error.
```python
from docarray.documents import ImageDoc
from docarray.index import HnswDocumentIndex
index = HnswDocumentIndex[ImageDoc](work_dir='/tmp/test_index2')
index = HnswDocumentIndex[ImageDoc](work_dir='/tmp/test_index2') # second time is failing
```
The error is that hnswlib index file `.bin` is created in function `index()` but not `_create_index()`. Second time it tries to load `.bin` file from the `work_dir`, which doesn't exist.

fix: save index during creation for hnswlib

---

docarray/index/backends/hnswlib.py
tests/index/base_classes/test_base_doc_store.py
tests/index/base_classes/test_configs.py
tests/index/elastic/v7/test_column_config.py
tests/index/elastic/v7/test_find.py
tests/index/elastic/v7/test_index_get_del.py
tests/index/elastic/v8/test_column_config.py
tests/index/elastic/v8/test_find.py
tests/index/elastic/v8/test_index_get_del.py
tests/index/hnswlib/test_find.py
tests/index/hnswlib/test_index_get_del.py
tests/index/hnswlib/test_persist_data.py
tests/index/qdrant/test_filter.py
tests/index/qdrant/test_find.py
tests/index/qdrant/test_index_get_del.py
tests/index/qdrant/test_persist_data.py
tests/index/qdrant/test_query_builder.py
tests/index/qdrant/test_raw_query.py
tests/index/qdrant/test_text_search.py
tests/index/weaviate/test_column_config_weaviate.py
tests/index/weaviate/test_find_weaviate.py
tests/index/weaviate/test_index_get_del_weaviate.py

This is the additional fix for PR #1424 .
We need to pass `max_elements` in method `load_index()`, otherwise it's reset to 0.

fix: passes max_element when load index in hnswlib

---

docarray/index/abstract.py

Fixes a bug in Document Index where torch tensors that require grad were not able to be converted to np array

fix: torch tensor with grad to numpy

---

docarray/base_doc/any_doc.py
docarray/base_doc/doc.py
docarray/base_doc/mixins/io.py
tests/units/array/test_array_proto.py
tests/units/document/proto/test_document_proto.py

the goal of this pr is to allow AnyDoc to load any protobuf file without knowing the class beforehand
code example :
```python
from docarray.base_doc.any_doc import AnyDoc
doc = AnyDoc(hello='world')
print(f"doc= \n {doc}")
pt = doc.to_protobuf()
print(f"pt= \n {pt}")
doc2 = AnyDoc.from_protobuf(pt)
print(f"doc2= \n {doc2}")
assert doc2.dict()['hello'] == 'world'
```

feat: add config to load more field that the schema

---

docarray/base_doc/mixins/io.py
tests/units/document/proto/test_document_proto.py

This pr fixes several bugs related to proto.
```python
from typing import List
from docarray import BaseDoc, DocList
from docarray.documents import TextDoc
class TextDocWithId(TextDoc):
id: str
class ResultTestDoc(BaseDoc):
matches: List[TextDocWithId]
da = DocList[ResultTestDoc](
[
ResultTestDoc(matches=[TextDocWithId(id=f'{i}') for _ in range(10)])
for i in range(10)
]
)
DocList[ResultTestDoc].from_protobuf(da.to_protobuf())
```

fix: from proto for nested List and Dict

---

docarray/utils/find.py
tests/units/util/test_find.py

Return a doclist of same type as the input index in `find()` and `find_batched()`.

fix: return doclist of same type as input index in find and findbatched

---

docarray/array/doc_list/io.py

To avoid this warning, use `pd.concat()`:

fix: use `pd.concat()` instead `df.append()` in `to_dataframe()` to avoid warning

---

docarray/base_doc/doc.py
tests/units/document/test_base_document.py

this PR fix calling `dict` on a document that contain a nested DocList.
Now when calling `dict` with a nested DocList the dict results will be a list of dict whereas before it was just the DocList.
Fix the real problem that was hidden under this issue https://github.com/docarray/docarray/issues/1474 
```python
class SimpleDoc(BaseDoc):
simple_tens: NdArray[10]
class NestedDoc(BaseDoc):
docs: DocList[SimpleDoc]
hello: str = 'world'
nested_docs = NestedDoc(
docs=DocList[SimpleDoc]([SimpleDoc(simple_tens=np.ones(10)) for j in range(2)]),
) 
nested_docs.dict() # use to fail now is working
```

fix: fix to dict exclude

---

docarray/array/doc_list/doc_list.py
docarray/base_doc/doc.py
tests/units/array/test_array.py
tests/units/document/test_base_document.py

this pr is fixing : https://github.com/docarray/docarray/issues/1501
it allow to do 
```python
from docarray import DocVec, BaseDoc, DocList
from docarray.documents.image import ImageDoc
class Request(BaseDoc):
images: DocList[ImageDoc]
images = DocList[ImageDoc]([ImageDoc(url=f'http://url.com/{i}.png') for i in range(10)])
request = Request(images=images)
request.json()
```
without having an error
* when calling `json` it manually deal with the nested DocList, otherwise Pydantic does some weird logic because it think it is a List (which is it)
* Custom validation on DocList. Now if the input is not a DocList but a list of dict lets say, it will try to validate every member of the iterable with the `doc_type` and then create a DocList out of it

fix: fix nested doc to json

---

.github/workflows/force-docs-build.yml

fix : https://github.com/docarray/docarray/issues/1508
somehoe docs build dosn't work and copy past tmp_docs into the old docs folded instead of replacing it

chore: fix cd for documentation

---

docarray/typing/tensor/torch_tensor.py
tests/units/typing/tensor/test_torch_tensor.py

Detach `TorchTensors` before converting to `numpy` for serialization. 
Change is only needed for PyTorch as Tensorflow operates differently afaik. I have tried different initialization for tensorflow and the below serializing script worked without any error.
```python
import time
from docarray import BaseDoc
from docarray.typing import TensorFlowTensor
import tensorflow as tf
class MyDoc(BaseDoc):
x: TensorFlowTensor
y: TensorFlowTensor
x = tf.Variable(3.0)  # trainable: Default: `True`, GradientTapes automatically watch uses of this variable.
with tf.GradientTape() as tape:
y = x**2
doc = MyDoc(x=x, y=y)
doc.json()
@tf.function
def square(a):
return a**2
x = tf.Variable(tf.random.normal((3, 2)))
with tf.GradientTape() as tape:
y = square(x)
doc = MyDoc(x=x, y=y)
doc.json()
x = …
```

fix: detach the torch tensors

---

docs/user_guide/storing/doc_store/store_jac.md

This information is for `store_s3`, but wrongly copied to `store_jac` I believe.

docs(store_jac): remove wrong info

---

docarray/array/doc_vec/column_storage.py
tests/units/array/stack/storage/test_storage.py
tests/units/array/stack/test_array_stacked.py

Before this, calling `doc.dict()` when `doc.is_view() == True` would return an empty dict.
The core issue is that the `ColumnStorageView` did not behave like a proper dict: `.values()` and `.keys()` were not implemented, and would return empty values.
That is fixed in this PR.

fix: dict method for document view

---

CONTRIBUTING.md

The section in CONTRIBUTING.md about building docs locally was not quite right and contained sections from docarray v1. These instructions should work now.
@Tanguyabel could you double check for me?

docs: update doc building guide

---

README.md

This PR brings changes to the docs where we mention type coercion for Tensor, with an example.

docs: add mention and example for type coercion

---

CONTRIBUTING.md
docarray/index/abstract.py
docarray/index/backends/hnswlib.py
docarray/utils/_internal/_typing.py
tests/index/hnswlib/test_index_get_del.py
tests/units/util/test_typing.py

This pull request resolves the TypeError in BaseDocIndex._flatten_schema that occurs when a non-class type, such as List[str], is used as an argument for issubclass(). As observed in issue #1557, this causes the HnswDocumentIndex initialisation to crash.
As Johannes suggested, I use a custom issubclass function that can handle non-class types by returning False instead of failing. This change prevents crashes when a non-class type is passed as input.

fix: support list in document class (#1557)

---

docarray/utils/find.py
tests/index/in_memory/test_in_memory.py

This PR filters out None embeddings when computing the index matrix before doing the NN search in `find` method

fix: fix None embedding exact nn search

---

docarray/base_doc/mixins/io.py
tests/units/array/test_array_from_to_pandas.py

In Issue #1584, we encountered a problem where the program would crash when the document contained non-class objects during the exportation of JSON/Pandas tables. The safe version of subclass method fixes this bug.

fix: solve issues caused by issubclass

---

docs/user_guide/storing/first_step.md

Fix the fact that InMemoryExactNNSearch is not listed as supported index

docs: add in memory to documentation as list of supported vector index

---

docarray/index/backends/hnswlib.py
tests/index/hnswlib/test_find.py

Before, running `find` or `find_batched` on a HNSWLibIndex, the search would raise an Exception from the hnswlib. This PR fixes it by limiting the `limit` parameter to the actual number of Documents in the index

fix: hnswlib must be able to search with limit more than num docs

---

.github/ISSUE_TEMPLATE/bug-v1.yml
.github/ISSUE_TEMPLATE/bug-v2.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

I am basically copying what pydantic repo is doing for handling issue because it is super helpfull
https://github.com/pydantic/pydantic/issues/new/choose
https://github.com/pydantic/pydantic/issues/new?assignees=&labels=bug+V2%2Cunconfirmed&projects=&template=bug-v2.yml
This just looks too nice to not have it
PS: I am citing the original issue template to give credit to pydantic

chore: add a better looking issue template

---

docarray/index/backends/elastic.py
docarray/index/backends/weaviate.py
docs/how_to/multimodal_training_and_serving.md

https://github.com/docarray/docarray/issues/1620
two non-breaking changes:
1. build() is more flexible and follows abstract signature
2. query_builder's `find()` can receive search_field even though it won't / can't use it

refactor: minor changes in weaviate

---

docarray/helper.py
docarray/index/backends/in_memory.py
tests/index/in_memory/test_in_memory.py
tests/index/in_memory/test_persist_data.py
tests/index/in_memory/test_subindex.py
tests/units/test_helper.py

Currently, the subindex feature is not available on exact in-memory NNIndexer. This PR aims to support nested documents for ExactNNIndexer

feat: support subindex on ExactNNSearch

---

docs/user_guide/storing/index_qdrant.md

```python
from typing import Optional
from docarray import BaseDoc
from docarray.index import QdrantDocumentIndex
from docarray.typing import NdArray
class MyDocument(BaseDoc):
title: str
title_embedding: NdArray[786]
image_path: Optional[str]
image_embedding: NdArray[512]
qdrant_config = QdrantDocumentIndex.DBConfig(":memory:")
doc_index = QdrantDocumentIndex[MyDocument](qdrant_config)
```
This snippet from our docs doesn't work, ":memory:" gets assigned to index_name instead of location.

docs: qdrant in memory usage

---

docarray/array/doc_vec/doc_vec.py
docs/user_guide/sending/serialization.md
tests/units/array/stack/test_proto.py

This allows `DocVoc` to be deserilzed to a specific `tensor_type`, i.e. torch, tf, or numpy:
```python
class MyDoc(BaseDoc):
tensor: TensorFlowTensor
da = DocVec[MyDoc](...)  # doesn't matter what tensor_type is here
proto = da.to_protobuf()
da_after = DocVec[MyDoc].from_protobuf(proto, tensor_type=TensorFlowTensor)
assert isinstance(da_after.tensor, TensorFlowTensor)
```
Note that the `tensor_type` passed to `from_protobuf()` does not need to match the tensor type from before serialization.
Since all tensor are represented the same way in the proto, any proto can be deserialized to any tensor type.
**TODO**:

feat: tensor type for protobuf deserialization

---

docarray/index/abstract.py
docarray/index/backends/elastic.py
docarray/index/backends/hnswlib.py
docarray/index/backends/in_memory.py
docarray/index/backends/qdrant.py
docarray/index/backends/weaviate.py
docarray/utils/_internal/_typing.py
tests/index/elastic/v7/test_find.py
tests/index/elastic/v7/test_subindex.py
tests/index/elastic/v8/test_find.py
tests/index/elastic/v8/test_subindex.py
tests/index/hnswlib/test_find.py
tests/index/hnswlib/test_subindex.py
tests/index/in_memory/test_in_memory.py
tests/index/in_memory/test_subindex.py
tests/index/qdrant/test_find.py
tests/index/qdrant/test_subindex.py
tests/index/weaviate/test_find_weaviate.py
tests/index/weaviate/test_subindex.py

This PR is designed to enable the indexer (for all supported backends) to check whether a document has already been indexed. We aim to accommodate various backends including in_memory, hnswlib, elastic, qdrant, and weaviate. Given that different backends store and index documents in distinct ways, we need to custom-tailor our function for each backend.
Progress:

feat: check if a document is already index

---

docarray/index/backends/in_memory.py
docs/user_guide/storing/index_in_memory.md

The InMemoryExactNNIndexer gets an attribute in `__init__` instead of following the pattern of using `DBConfig`.
Waiting for #1648 to be merged updating Documentation

refactor: implementation of InMemoryExactNNIndex follows DBConfig way

---

docarray/utils/find.py
tests/units/util/test_find.py

I was trying to wrap the InMemoryExactNNIndexer as an Executor in Jina and passing limits as parameters they are passed as `floats` because of protobuf. So it would be good for us to have this change applied otherwise it raises an exception

fix: pass limit as integer

---

docarray/base_doc/mixins/io.py
docarray/helper.py
docarray/utils/_internal/_typing.py
docs/user_guide/sending/serialization.md
tests/units/array/test_array_from_to_bytes.py
tests/units/array/test_array_from_to_csv.py
tests/units/array/test_array_from_to_json.py
tests/units/array/test_array_from_to_pandas.py
tests/units/array/test_array_proto.py

This bug is caused by the deserialization process. The deserialization function currently only checks the schema of the class, without specific information about the particular document type in the field of union type. To resolve this issue, we may need to modify the data storage. After discussing with Joan, we could temporarily remove support for the union type and add this info the document. Additionally, we provide users with a more informative error message.

fix: bugs when serialize union type

---

docarray/array/doc_vec/column_storage.py
docarray/computation/abstract_comp_backend.py
docarray/computation/numpy_backend.py
docarray/computation/tensorflow_backend.py
docarray/computation/torch_backend.py
docarray/helper.py
tests/units/array/stack/test_array_stacked.py

Before this, DocVec equality checks that involved a tensor would fail by raising and Exception:
```python
class Text(BaseDoc):
tens: TorchTensor
da = DocVec[Text](
[Text(tens=[1, 2, 3, 4]) for _ in range(10)], tensor_type=TorchTensor
)
da2 = DocVec[Text](
[Text(tens=[1, 2, 3, 4]) for _ in range(10)], tensor_type=TorchTensor
)
assert da == da2  # would raise
```
```terminal
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```
This is because checks of the form `tens1 == tens2` return a boolean tensor, not a single bool, which breaks an assumption in the previous implementation.
This PR solved that by introducing a helper function that let's us compare tensors and get a single bool as output.

fix: docvec equality if tensors are involved

---

README.md

`Coming from a vector database` needs adjusting in the readme

docs: fix a reference in readme

---

docarray/index/abstract.py
docarray/index/backends/weaviate.py

```python
if isinstance(docs, List):
docs = self._dict_list_to_docarray(docs)
```
_dict_list_to_docarray expects a list of dictionaries which is then transformed into a DocList. However, since DocList extends List, the condition is true even if docs is already a DocList, which then leads to an error.
We already fixed this in one place but there are other parts too that need an extra check.
Found while working on milvus pr

fix: avoid converting doclists in the base index

---

docarray/array/list_advance_indexing.py
docarray/computation/abstract_comp_backend.py
docarray/index/backends/in_memory.py
docarray/typing/tensor/tensorflow_tensor.py
docarray/utils/find.py
tests/index/in_memory/test_in_memory.py
tests/index/weaviate/docker-compose.yml

Allows to do easy search in Memory when AnyEmbedding is used as with `TextDoc` or `ImageDoc`:
```python
index = InMemoryExactNNIndex[TextDoc]()
docs = DocList[TextDoc](
[TextDoc(text='hey', embedding=np.random.rand(128)) for _ in range(200)]
)
index.index(docs)
res = index.find_batched(docs[0:10], search_field='embedding', limit=5)
```

fix: fix search in memory with AnyEmbedding

---

docarray/index/backends/qdrant.py
tests/index/qdrant/test_configurations.py

qdrant doc index does not recognize index_name when passed
```python
from docarray import BaseDoc
from docarray.index import QdrantDocumentIndex
class SimpleSchema(BaseDoc):
title: str
index = QdrantDocumentIndex[SimpleSchema](index_name='index_name')
print(index.index_name)
```
will print `simpleschema`

fix: qdrant unable to see index_name

---

docarray/index/backends/weaviate.py
tests/index/weaviate/test_column_config_weaviate.py

WeaviateDocumentIndex capitalizes the index name when creating an index, so if we pass lowercase index name, there's a mismatch leading to various errors
```python
from docarray import BaseDoc, DocList
from docarray.index import WeaviateDocumentIndex
from docarray.typing import NdArray
from pydantic import Field
class MyDoc(BaseDoc):
title: str
embedding: NdArray[128] = Field(is_embedding=True)
docs = DocList[MyDoc](MyDoc(title=f'title #{i}', embedding=np.random.rand(128)) for i in range(10))
doc_index = WeaviateDocumentIndex[MyDoc](index_name='zdzd')
doc_index.index(docs)
query = np.ones(128)
retrieved_docs = doc_index.find(query, limit=10)
```
> File "/Users/jinaai/Desktop/docarray/docarray/index/backends/weaviate.py", line 354, in find
> docs, scores = self._find(
> …

fix: weaviate handles lowercase index names

---

docarray/index/backends/in_memory.py
tests/index/in_memory/test_in_memory.py

Support arbitrary number of find/filter operations for `InMemoryExactNNIndex`, enabling pre+post filtering
From now on, you can build queries like this:
```python
query = (
doc_index.build_query()
.filter(filter_query={'price': {'$lte': 3}})
.find(query=np.ones(10), search_field='tensor')
.filter(filter_query={'text': {'$eq': 'hello 1'}})
.build()
)
```
Note:
**how limits work**
Since developers could provide `limit` in any component of the query, and we also had an internal default value for `find`, the results were confusing. What I'm doing is the following: I'm not applying any limits during the operations, but I'm remembering the lowest one provided, and apply that limit in the end.

feat: InMemoryExactNNIndex pre filtering

---

docarray/index/backends/qdrant.py
tests/index/qdrant/test_subindex.py

The subindex is initialized with a different_index name, so we need to make sure that the collection name is updated accordingly in the constructor.

fix: collection and index name in qdrant

---

docarray/index/backends/in_memory.py
tests/index/in_memory/test_index_get_del.py

Implements Update for `InMemoryExactNNIndex` by creating a mapping between document IDs and their corresponding positions in the DocList.
In terms of performance, we see significant ~130x (from 0.0266s to 0.0002s) improvement in get, and a slight increase in the index time - approx. from 3.50s to 3.57s; Other operation times stayed very similar. Experiment was made on 200 000 docs, vector dim 128.

feat: update for inmemory index

---

docarray/index/backends/hnswlib.py
poetry.lock
pyproject.toml
tests/index/hnswlib/test_filter.py
tests/index/hnswlib/test_find.py
tests/index/hnswlib/test_query_builder.py

Support Filtering for `HnswDocumentIndex`, separately as well as inside the query builder
Main changes:
- Add filtrable fields separately to the sqlite table (so now we store `id`, `doc_blob`, and fields that can be filtered)
- Support `filter` function which does not touch hnsw and executes filtering on the sqlite table
- Refactor the query builder (hybrid search) to enable pre+post filtering. Post filtering is done in the same way; Pre filtering first queries the SQL table, gets hashed_ids for the filtered documents, and passes it to hnsw's new feature that can filter vectors based on their ids during search. 
Notes:
query builder became quite complex even tho I tried decomposing it as much as possible.
i think codecov has some problems?

feat: filtering in hnsw

---

docarray/array/doc_list/doc_list.py
docarray/array/doc_list/io.py
docarray/array/doc_vec/doc_vec.py
docarray/array/doc_vec/io.py
docs/API_reference/array/da.md
docs/API_reference/array/da_stack.md
docs/data_types/table/table.md
docs/user_guide/sending/serialization.md
tests/units/array/test_array_from_to_bytes.py
tests/units/array/test_array_from_to_json.py
tests/units/array/test_array_from_to_pandas.py
tests/units/array/test_array_save_load.py

closes #1677 
The approach is to create a separate IO Mixin class for DocVec that takes a tensor_type argument for all deserialization operations.

feat: tensor_type for all DocVec serializations

---

docarray/typing/tensor/abstract_tensor.py
tests/units/typing/tensor/test_tensor.py

Currently the following raises and exception:
```python
from docarray.typing import TorchTensor
TorchTensor == type
```
```terminal
Traceback (most recent call last):
File "/home/johannes/.config/JetBrains/PyCharmCE2023.2/scratches/scratch_183.py", line 3, in <module>
TorchTensor == type
File "/home/johannes/Documents/jina/docarrayv2/docarray/typing/tensor/abstract_tensor.py", line 101, in __eq__
if cls._equals_special_case(other):
File "/home/johannes/Documents/jina/docarrayv2/docarray/typing/tensor/abstract_tensor.py", line 62, in _equals_special_case
is_tensor = is_type and AbstractTensor in other.mro()
TypeError: descriptor 'mro' of 'type' object needs an argument
```
This fixes that

fix: tensor equals type raises exception

---

docarray/utils/create_dynamic_doc_class.py
tests/units/util/test_create_dynamic_code_class.py

the following case results in a KeyError:
```python
from docarray import BaseDoc
from docarray.utils.create_dynamic_doc_class import create_base_doc_from_schema
class Nested2(BaseDoc):
value: str
class Nested1(BaseDoc):
nested: Nested2
class RootDoc(BaseDoc):
nested: Nested1
new_my_doc_cls = create_base_doc_from_schema(RootDoc.schema(), 'RootDoc')
```
the reason is, `create_base_doc_from_schema` will keep referring to `definitions` field of the traversed schema when creating its corresponding model. However, the `definitions` field only exists for the root schema

fix: fix dynamic class creation with doubly nested schemas 

---

docarray/index/backends/qdrant.py
tests/index/qdrant/test_configurations.py

**Issue Resolved:** Issue with Defining Index of Type `QdrantDocumentIndex` for Documents with Non-Class Type Fields
**Description:**
This pull request addresses the issue where defining an index of type `QdrantDocumentIndex` for documents containing fields with non-class types resulted in a `TypeError`. The issue has been resolved by replacing the usage of `issubclass` with `safe_issubclass`

fix(qdrant): fix non-class type fields #1748

---

docarray/array/doc_list/io.py
docs/user_guide/sending/serialization.md
tests/units/array/test_array_from_to_json.py

**💥 Contains breaking change**
This changes the return type of `DocList.to_json()` *and* `DocVec.to_json()` from bytes to str, by decoding the bytes output obtained from the `orjson` library.
This is done to make it consistent with `to_json()` on `BaseDoc` and in pydantic.
`from_json()` does not need to be touched, since orjson happily accepts strings as well.
This decoding step incurs a small performance penalty:
Running this multiple times I saw a **`to_json()` performance penalty of 8-15%**, depending on the run.
The **`to_json()`/`from_json()` roundrip penalty was consistently single digit percent**, presumably because the  `from_json()` call dominates this runtime.
**Note** the **breaking change** this induces in cases like the one shown in the documentation that is also changed as …

fix: make DocList.to_json() return str instead of bytes

---

docarray/documents/audio.py

* Adds field descriptions and example usage of each field for the predefined `Audio` document

docs: adding field descriptions to predefined audio document

---

docarray/documents/image.py

* Adds field descriptions and example usage of each field for the predefined `Image` document

docs: adding field descriptions to predefined image document

---

docarray/documents/text.py

* Adds field descriptions and example usage of each field for the predefined `Text`

docs: adding field descriptions to predefined text document

---

docarray/documents/video.py

* Adds field descriptions and example usage of each field for the predefined `Video` document

docs: adding field descriptions to predefined video document

---

docarray/documents/point_cloud/point_cloud_3d.py

* Add Field Description and examples to predefined `PointCloud3D` document #1736

docs: adding field descriptions to predefined point cloud 3D document

---

docarray/documents/mesh/mesh_3d.py

* Add Field Description and examples to predefined `Mesh3D` document #1736

docs: adding field descriptions to predefined mesh 3D document

---

docarray/index/backends/milvus.py

fix: milvus connection para missing

---

docarray/array/any_array.py
docarray/array/doc_list/doc_list.py
tests/units/document/test_doc_wo_id.py

DocList[BaseDocWithoutId] was failing. This pr fixed it

fix: make DocList compatible with BaseDocWithoutId

---

docarray/base_doc/doc.py
docarray/typing/tensor/image/image_tensor.py
tests/units/array/test_array_from_to_pandas.py

DocVec nested document could not serialize correctly using `model_dump` from pydantic v2. 
This pr fix it by recursively deep copying the document whereas before it was just done at level 1

fix: allow nested model dump via docvec

---

.github/workflows/ci.yml
docarray/base_doc/doc.py
docarray/base_doc/mixins/io.py
docarray/display/document_summary.py
docarray/helper.py
tests/units/array/test_array_from_to_pandas.py
tests/units/typing/tensor/test_ndarray.py

We perform a check that doesn't work anymore with new versions of numpy, because they switches equality semantics to broadcast over every element in the array.
This PR fixes that by treating np arrays as a special cases in the affected check. It also does the same for tf, torch, and jax, just because == semantics on tensor-like objects can always be a bit surprising.
The numpy version in question (`1.26.1`) doesn't support Python 3.8 or down, but we do. Therefore, poetry can't lock to that version. To circumvent this, I am here manually installing the "problematic" numpy version in the CI. For the same reason **I am bumping some tests to run on Python 3.9**.
No new tests since the existing tests already fail with the numpy version in question, and are fixed by the fix (see failing check …

fix: from_dataframe with numpy==1.26.1 and type handling in python 3.9

---

CONTRIBUTING.md

The command is not correct in the CONTRIBRUTING.md file
in this commit the command is corrected in the file

docs: fix sign commit commad in docs

---

docarray/typing/tensor/torch_tensor.py
tests/integrations/typing/test_torch_tensor.py

Issue no : #1831 
The primary purpose of adding the __deepcopy__ method is to provide a more controlled and tailored approach to deep copying instances of the TorchTensor class. This helps prevent any unexpected behaviors arising from shared references to the same memory.

fix: fix storage issue in torchtensor class

---

tests/integrations/typing/test_torch_tensor.py

@samsja ,
Could you please check the PR and let me know if is there any issue :)

refactor test of the torchtensor

---

docarray/index/backends/helper.py
docarray/index/backends/mongodb_atlas.py
pyproject.toml
tests/index/mongo_atlas/__init__.py
tests/index/mongo_atlas/conftest.py
tests/index/mongo_atlas/test_find.py
tests/index/mongo_atlas/test_persist_data.py
tests/index/mongo_atlas/test_query_builder.py
tests/index/mongo_atlas/test_subindex.py
tests/index/mongo_atlas/test_text_search.py

This pull request adds `QueryBuilder` functionality to the existing  `MongoDBAtlasDocumentIndex`.
```python
from docarray.index import MongoAtlasDocumentIndex
NDIM = 10
class MyDoc(BaseDoc):
text: str
embedding: NdArray[NDIM]
number: int
docs = [MyDoc(text=f'text {i}', embedding=np.random.randn(NDIM), number=i) for i in range(5)]
index = MongoAtlasDocumentIndex[MyDoc](mongo_connection_uri='localhost')
index.index(docs)
query = (
index.build_query()
.find(query=np.ones(NDIM), search_field='embedding')
.filter(query={"number": {"$gt": 0}})
.text_search(query="text 3", search_field='text')
.build(limit=n_docs)
```
Atlas offers full-text, vector, and hybrid search. 
For documentation, see the following.
* Text Search: …

Adds QueryBuilder to MongoDBAtlasDocumentIndex

---

docs/user_guide/storing/doc_store/store_s3.md
docs/user_guide/storing/index_elastic.md
docs/user_guide/storing/index_milvus.md
docs/user_guide/storing/index_qdrant.md
docs/user_guide/storing/index_weaviate.md
tests/index/elastic/fixture.py
tests/index/qdrant/fixtures.py
tests/index/weaviate/fixture_weaviate.py
tests/integrations/store/test_s3.py

Use `docker compose` inplace of `docker-compose` to fix tests failures
- find and replace `Docker-Compose` -> `Docker Compose`
- find and replace (note the whitespace) `docker-compose ` -> `docker-compose `
- Remaining `docker-compose` in the repo are either paths or files
`docker-compose` has been removed since 2024-04-01
https://github.com/actions/runner-images/issues/9557

fix: use docker compose
